apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: fleet
  name: fleet
  namespace: fleet
spec:
  ports:
  - name: 3000-3000
    nodePort: 3000
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: fleet
  type: NodePort
status:
  loadBalancer: {}
