apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: sql
  name: sql
  namespace: fleet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sql
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sql
    spec:
      containers:
      - image: mysql:5.7
        name: sql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: fleet-secrets
              key: mysql_password
        ports:
        - containerPort: 3306
          name: sql
        resources: {}
        volumeMounts:
        - name: sql-pv
          mountPath: /var/lib/mysql
      volumes:
      - name: sql-pv
        persistentVolumeClaim:
          claimName: sql-pvc
status: {}
