apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: sql
  name: mysql
spec:
  ports:
  - name: 3306-3306
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: sql
  type: ClusterIP
status:
  loadBalancer: {}
