apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sql-pvc
  namespace: fleet
  labels:
    app: sql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1000M
