apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: discord-opsbot
  name: discord-opsbot
  namespace: persistent-outreach
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discord-opsbot
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: discord-opsbot
    spec:
      serviceAccountName: discord-opsbot
      volumes:
      - name: discord-opsbot-admins
        secret:
          secretName: discord-opsbot-admins
      - name: gcp-serviceaccount
        secret:
          secretName: nebula-sql-backup-gcp
      containers:
      - image: ghcr.io/persistentss13/outreach-discord-opsbot:0.1.0
        name: outreach-discord-opsbot
        volumeMounts:
        - name: discord-opsbot-admins
          mountPath: "/app/config"
        - name: gcp-serviceaccount
          mountPath: "/etc/gcp-sa"
        env:
        - name: NAMESPACE
          value: persistent-outreach
        envFrom:
        - secretRef:
            name: discord-opsbot-token
        - secretRef:
            name: nebula-sql-backup-gcs
        resources: {}
status: {}
