apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: discord-opsbot
  namespace: persistent-outreach
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: discord-opsbot
subjects:
- kind: ServiceAccount
  name: discord-opsbot
  namespace: persistent-outreach
