apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: discord-opsbot
  namespace: persistent-outreach
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
  - list
  - create
- apiGroups:
  - apps
  resources:
  - deployments
  resourceNames:
  - discord-opsbot
  verbs:
  - get
