apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ghost
  name: ghost
spec:
  containers:
  - image: ghost
    name: ghost
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
