apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nebula-sql-pvc
  namespace: persistent-outreach
  labels:
    app: nebula-sql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1000M
