{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "./rules",
    "namespace": "default",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "./rules",
        "namespace": "default",
        "creationTimestamp": null
      },
      "data": null
    },
    "encryptedData": {
      "rules.html": "AgDFyA8/84kcD2SY4K4HtKQrqIMyJXnq4ogr+3gj/lM4MmrzGGU7Qu2Phw/nkDDKyFHETWM4oGR/wU+f9n51nTF7ifLKRfYGjJ9Vhz2A4cknykjixcnKCzhMZgIiCigNzEy9yYRLXhv7QG3WLnGxbyUQLWEnh8vxmfSWn2WOuwQPq4jOOuFnPkXFh/LwMVD0d+2gOaaSfwE4IjMQ9bJpFQu5NVaYtkUaKm3YtQyFmRNVhAxcc9vocycw+zNC2B+H9pwsMxRRM6WSXfy+BBS9X9C7z5Tl3PkIMRHaIaM77lCTQIDU5zZDxM6i1s2WDVRMob7csA7h0e0PEUzaJ+L5BqGqWSwEfwXVHrR86qQb29Z9mRg/KEnnYrAuuf8lelxJVTxUO301M/DyZmAYBqEMBW4pvvJcHF01fqoI6s2F8e/JSwPbVVM7aDj0wOoOj9/l5E+YO6w6yFHZogxVJQGW1SGFIVy3knfWv3448FqMVzxlMj87fxCRhcEU2s9LUa545xvu+7pxnn2HUMqx75ALo32ca6FFD5bIZIPdvqg2GvKyHuU872WcdTT/HY5HMl7GfC2PRjdEU0CQMpaj/TtCSvHa0r34kUnDfpZEttjB/aJ0ZZTc2qh2RVRas++3BWOGbSHdHG0jYxqTepUAZtZenpgcNYz+YdnI5o9J5pmbOCw9lbWKNGzMEwHavNYHGudwwOFtqGR1x1PtgghNocrIoUv8LYSTi7pl1LngOojsnBKopntvVXgutIYti/nOEc/cjghQHf8XG2Oe60jgRZ0eh0FKyUZSQCnWNepKjnvJVibw8X9WO/IxVv7XCkK2yI0acP+ae1xEGJvjvL/NdDUUd92eRjEF9KsxE3pZlwt7yul+Wn9XJhYtmgVLLFFU8farN8fvb3bnQ/aBDvWSqm7P7obDbu4lNDOBanON5Cgl9Ff4noQN30W6jswXitDRdFIYtpA5CW+H0R+wFTqKeLgOSC66q8oFoASMAcf+Dt+qsex4Z334f+pBQbZvc+09vkLrF+upvMubheUInv+4PT320mHyFh/noFKU8PcZAb8pvJqvlzRUCcB0fNZ/1vdJc5UT0Ep2"
    }
  }
}
