{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "./space_ruin_blacklist",
    "namespace": "default",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "./space_ruin_blacklist",
        "namespace": "default",
        "creationTimestamp": null
      },
      "data": null
    },
    "encryptedData": {
      "space_ruin_blacklist.txt": "AgCNLYCsdwoqekNF1g7iIgYzjUR51pO8XfcUHnFCRHuRw06eHqT40Gc7UZBZ8oGpMKcSqbvdd/ExpwS+Zo9xTxKUG+kYxqDBqwD0WcQ78EX3CMtCnTpcDiiBH8/S7YfGrD4e8r4mxRUCzp+t+8GkzTq1eW5r9kiEN4llrayiw9aiXEqiP9cCsc69bxobsllvxl5XaWO+wSh8Pqt++IwuJ1hQjCQQv/uEpvkEBN67fCBuaIUybPQc+ujU+P6EE0i+Vnc1DXhLufLQs1Kao6zIh6dDGm6cQ2wXykzZPc2L5h7mJrWnFCnvsiLqP7lIyxHrnk3efl5dNPEOea4jTVVGjb/KJayI/snqPVxHrLZmVyNMcndCg7GMyq1MsNJUkWhizDwFHG0r0jrxsO2EyOYDpBvGZQmqx22cfmcqjmcpr7pOxTPGirz5n1E4vWxpynfCFE3uJHkreNb5xvYb2ND+RHEtgXOltYUbi59CIZH+ihU71TUbXxFWrvjPU7DpTob6pA+ygpnuDeKlMsAnt/R6bgZY4MnTuWCKEW3G01iai9quIo8JM5HBKAX07lvgm6p/tDSrpeSfXtuVHBzEBQQ1htTxS1cBmiErgNcCePFQcfCGqz6qDXnXnJbkmBlZ7JOeSMNCG5QkrrUME6/sWewPZTv2g8aNFjsVbR7vfEKGhObc+KtEl3sNltnfg6SgmxUUUiEApYIeJOtnc6QEdrN4Bkg4fPR0u5HK8TYr1fT2un9lh8VVwyYaoGlwi8PG36xdt0TrC8K9sX9OmLCR8STxLIZKHgBN8xc1sfqR+aIYNdD6ofy49KpZdb0HMnlKLvOfI9YB9BqxhxabkY8nmaKeCuDwR6Y2qx8Xy/kVLP+QCxIQ+fkOBSfqAEP6AwkFzkITqusy9861OlXczRwZCxGfAmQWthQqvx5JtCD9cL2V8XHudkj46G+pTzkavGcpcJA+zY62kuI5uMHSyBAwCU3s8lS65A=="
    }
  }
}
