{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "./alienwhitelist",
    "namespace": "default",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "./alienwhitelist",
        "namespace": "default",
        "creationTimestamp": null
      },
      "data": null
    },
    "encryptedData": {
      "alienwhitelist.txt": "AgAoHEGEEHMn9CJMMwzq+eNu5StEX4TMuQxZkAhH9Bm7mUzqf0sP+vixIwKPOiPs6p+r5eyRawScvh5gymR4dVfpfJ94sDM+axnkeNEzoV9t/ON8+PWurLfNsOeY+EXhZTNMsceusLxf83wU1GXueoU9oNWAlEXedLMCCc1AgauzZDFRCM2YuadZG+xbZK7AL+Pp8NlTcxb3m4HV8f6EVU4PMG5m597AAyXlv+SNFgoe3gpPuMXzSiNxfB+dzGrBuEPSKhpfX0fNL5PiF6xvXmhFq689yJsHc7wlNU+ljOKPplTqskaAu7JcCQk+q/MEtByucnvoyNY5NyEA8IvrArVeeNmqnUUA5JyZIgwQ18bZtEXhDveIW3JqtqxTEMH23hFouFpg1t/VpWvCCGg2PW5IsPWv176o5eagpVa7L3J4MUqdEc/ApsuWAct9We+c8Uaa/pz1xmrB5taKWxOB9cCSLdMIJcd3uEIjgYD7YeetxO32BzXax5metDeIgkjmyDuF/bh4/DV5ftOBXZBfLvhraXluYzmd6fF/AKZaYmA/GqNSXoVEaRbDrCOLH7k+jgyfLTdiDE6wc3PCxse45c+RQoMkQufHn8WEvUxu+oKlTiRVD9j6XqjlZOMHRl+oEWkUG0ph7hUVv/T9Zb5sjQH/JD1Yu2osxBwkFKGtW4kdDX9J4BpiGoNpmE11vmlgsn/AI4HyCKQolLS1Hsyp0FUzS5pl"
    }
  }
}
