{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "./dbconfig",
    "namespace": "default",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "./dbconfig",
        "namespace": "default",
        "creationTimestamp": null
      },
      "data": null
    },
    "encryptedData": {
      "dbconfig.txt": "AgC7m1D2qmxMWGAKGbOYc9Rzfgt3GSRMSSANjFiJqQ1QOY7o3+kq8O87ANMHmEZLjl4T4xiIg4RhTM8bov0KC/wtX+TBpgM4hZYxnWX3DYVoZybJflG+qTG2eG+BUzwjq7NbzRRoGjuqGHDEWnsjMCj06YZppz++6LtlpPk73fGKCyhCqEM/mISttsr0c7HI7PhfGz3ARdCC9bYJj3+QrFns2CLU8N4keD5FAgkkIzu2xg57Smfoq2pRvF8JcheJzb7zg3vU7CMuYa5UMN0di11won3E/K9Cp3uIfSFUk/8aUh8iAK2F59aBtExe6wddF9LaIAQVAMliTOV6GS9QT4QWSEjvEkiWZXqTqNzxxO2/KfWzVvVg9lX3xYuEFy9GmqfrytFkHKLFR5WF1Ji1oPncnVtjzuzE1yfxTB/0oOa++yq7jzHfpxXQ51v6x4Y+4z2vrqUNZYW+l4z1NXwXgsEho3dNNg96Xl1mlXwT31wstmepqEKxV+cv9QIcF6QO/bqjgWHrz08b/UgLpZ6sWLtDgbNBQ5Su5UyKPeWNn7wtYZ9TOOHwu1xIQf/T7mmlN3zB5vY19GjnZKnVsjK0288+bAB3QBPzas9H1IDXlWvdw0yzebQaMQi/1GJA3hx2Tf7ao2LkMayoCOD+dFXTYe29iv0PlK+aGGCXel8Osic/QKD3XvoIZ38QhuHzxKOL8b9BjkoWkMIs6/EPF8yrTKU9Yn843E8xvk7591uk3pSGWl+zXlJqxzpQ2nckpkTJgcVqmgHbSL+ncXGC0BT3Ay57Yn3erzi+DtIc7R8fwVHxwx03U5zmAYfmTOii3uDt9WE4lYE446v31TRv9PrP9xCnePKDtKtNf5M+5cckhDSoqe7JMdR/Jd7iMDd4+7o7U17H4LsVEratlhMiWp4TFbu43fgO95OncmQ2R8vlAf1GGj/fOIABxbpyhtnisAfT/ppG6/Mq0p8XcvbmlCvZZiPd6qFixJlyxOIrRed+EFNw5MD1t/enHOkxEB32OTvof+izTuMM6TsCEfy8j/UdQ3rmQJk6JVz+eEkCXRwUHO3tKB7wvwlojE+UdqUbmcEzcVznIWefVO/yVgiRwJQsLDAQ8LE+4ZaT0zVzcKL2Y4frBCdMNVUjMUrZRXWjXprkyZ2GLTR+ovBjOhMeagpXUwMhC3BFOkl39RWH6jgtCySyV1uOiukIFMm8mVFjpeaZrOMKnza5xr20COLFfC4szflizAkNzCtLTlCpWr5GdoCASNvYqv9n6C9uIByY9fFwI3Nd2v0DmFHeT2MZW580P9GQPrPUWvqlo0Fn/eLw9Vs07a4PnT/POQGyTNuGEh4MDFxBOeuvAymxOP4QS97r0JZmArJhVje5imB+jpR5R6aHpvfqRS7lYbNBqsL78+gw2U7ismji3rQTnTmwStPs2nRbtIRoiRtVoEpo11ouAytHozOFUfkrV4BEyXaJMK+MjmCykpiG8L38TdG8xKESDhmY1tj9dpCxX9zrg8eWluCyPah4bYJHnU3nTioTrGx/2eg5FcPPH2nwbmozlOv/59zPhHL18J4DDaJUgN/M8ay5XD/ECGxFTZOW+b+tom13e0lHHLGLoNy9Ls842gCht5Bo6UDpOzhUGvXWYz5HgEYGyzqF8V9cwhhwm6rVLM0IbFXggdMOUqgaddo+ePvLpUAdvXb1RDYs8aExB8z60eLHr8/9W4PGcF1V/w=="
    }
  }
}
