{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "./webhooks",
    "namespace": "default",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "./webhooks",
        "namespace": "default",
        "creationTimestamp": null
      },
      "data": null
    },
    "encryptedData": {
      "webhooks.json": "AgCr7Lw+l5Vno3GdN2e5+Tjv4X+kvFXFPFg0QCWG/D2EEbkjv++uCGdWLdzzsMSSGmcDZ4d0o2rfUFaM9MClNGYEHD5wVhgu+dOMgwaeCpwtwHUULa5nSYUoS6efxD6+TgRC6utJMEoL1F14W1ffu+++J9qneUpFmYLQ8KmQMY/+1rccHQuJeUD5i6dlYEfQpjNfiLg1Gy97Nz2PWxGlA9zwEHvHQYhFhXD/TaGkXrUSKAXTLQM0ZRqDB3XqEV6l0/7Txsip9THyqhCXtIRBHD+QPyDAHVqZZhSNFvfT6f+vrBBWXqEImDXNI62pqdhxagrRKj34NiP0FvaMf/1QgZzKRekmdc0UNzbFAFQe6gLUW3C2OE5mYX/jGIecXmF0Cz06dhavxOCtGvpZnRXf+gMBkfzoDE5LX38nqkxXzmrF5hPmEYAR/T1kG57NessMGjcnzXXrPDqZHt6ipJvyA9V6FpvE4tKfRF5oKXk+Ber+KjwMwXfDTwdHY2MNE/j09Gxn7drZ2b5kMbjmlKtXU2nZStOK10618k4pme4gZlXXmhENEzpQsbInDJvHkefL5O3Z5wcTn3j/rwbZjbn9pcnB/FWynNFQCrOEpG9j+WewBu0CQoyz9AxE3N/Ow3Ldjp30Xlw4NEgdWKcvUyJxd84ye6gDrIvV7mZM38qtPpX5Cv2EI32Crkwxrpb+M+d8KHYLWeHLz9AT5/pxiXVmYPXUIwRT7f+lq65/G+s8uzBrZKTRLFd6e8gdREFRIG5s2/3rvDcrCoPSVk2essI7rrDIVsBFRBUQ4fBnvged3ZJSkablrjldbqrf5SmIcRqSzTM2zQJfvNvg6A3mXhrSvPx3sKL18FbDbBSeEYXUJTt+/t0RNJcjp8kqZhSBUPWPw4Zon6iasyyQeMzGNzwQpDDL7L87quXPg1y4UQjR3HoWNqPTDgGzsXvU8udiNlN2DWbCy5g5xNMZ4/w7PFLqL1299ZZl6sXdNwRT4aayTDAzJCry32EkXKM="
    }
  }
}
