{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "./moderators",
    "namespace": "default",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "./moderators",
        "namespace": "default",
        "creationTimestamp": null
      },
      "data": null
    },
    "encryptedData": {
      "moderators.txt": "AgCHD8cavi0kHLUspgnKBcnS3eYbsqII8ZC6Lgu1legFuyx8jfG4LE9fO98Em2ZYxQ5SmNw3RJ8Xb8uz0iZ1DlwIa4QbMGoymcudtzr9ni5aCv9pD9K1ailnXlPexfCyY5SDoL7mjzNqSxZDhyo2I5sIRJZ7cpr7T7r4jc4IuvIu37ix0OfZeskMcC0FzVERtLGcG18n8LwHp5dDGSGaqA+I0VDNiNhV6OFEB6r8rJajw/ytccbXE/Jqo0q8Bls5+uKNk5MIAjvamzLFzUMIw+z0KcqoqvJgiN7ngdOIfAUPwrY+OlyFFzdr7YNIlx61eKL1G5g7UY1kVSQn/qJ/+LX1cRJDatj2AXAVKb7kcscLBBzzSbMu2tvb6e6xWRJJB3EKNluEotRNJZjS/k5y7AWXx0f1c+1gFigWZ1EqE86ZuBUdCKyYOT9gcXC9nSOdEIOAm5LqyKCWnRUvS0KO9P8kkBlqo8yotfu6ZWGQNmzFMEsy2t7qkg3FyxT4XlnuvrUkiGkdXmvBG9/u6LpCaShlw2Ms5AsWVZ5ixKfIj7/eZMRiXPeBdstgSR3BwlQTk5mGMWM/b43QsC918gjwQjxOQIaQJU4I/ah1eD5IUP0bcVSKPz9t0KU4/201PyrFS5zAxyVQlIVoGmjERq3hIrnofetPRa+Kj022C9aQixSyxKEhranaCWABbAkRrf1jvr+71zyc7HDhbtq7iMyG22+CiCOg1oDkODSLf9OZUODnKTX1IYAPZcWCHMPXPfoghh7MsQ3jc+AnEEftdgHNNtTkBLEsAxtrt+GCHDgHopYAwCPSvAf5Q5oMce41KNHuHuU5cou6BlVJgPhc4tHFs/Ds8xAHCiZTGJmOWpTPxZl6Pw=="
    }
  }
}
