{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "./motd",
    "namespace": "default",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "./motd",
        "namespace": "default",
        "creationTimestamp": null
      },
      "data": null
    },
    "encryptedData": {
      "motd.txt": "AgDY4l2PoK5xh0ShZdTVwO46AsYtz1/41PRbsyAsRTGljfX1zdMK0iQBEqaFtwWkDxOAJJvHvU8EkDLsULvY7FJHvAtTD20T5GhYzyfs2VrQk9kOp0tp85MEI2vYWJgLo082IWD+y1u3HO6YKt1UXSie8Gnua8+7NA8d1Wblv5Tauv7p9ORKQk3+hI5mV+wCqvrTcmri9xPCkrLdU8ylSOHdPEPf6M1xJHpC7+EbsNbnvX0M0H/MrDkVW+aoonHS1XIDJqLQmzXdWVKX6lqF8JKpCxNJJhDTasnelTw9uiCSA/QxgXXdrTGikhesprPiOQX1xzxXZPQib4Sgt60mec75tGUuoskbRVntVvrJ+jhhLUHx6VQ1qFJIUrSVsVE7W1Z5rnGPBA3l8fV1LDChuoGfS+N2t3OUPCR+uLNF17eIUVYUrn3vhUOAIq1FHs63JKFRE3jm1CAqw93/0MD3yxSgS02Rl/u3+y1WqCtkXE23Eao8QoekViej9mWoQ0BqHm90wgWU6NU9RWYMJiLywoegrR2ZwkWQSpbRW3sOiXJ7zaFfIeAPU1bGfLo6/I42KYC99VcokW60TyS4FUZmozbT/pAwHyKit/1zCtK0AaCpMhS8md8Q6D5f3yUQmjIqGYWHUI2APvibrCv11B0IQmYVvTBYGjzuwFdp/L+JhW23OHdeFZBQnioXo2jltCyfZkUXQAjgDW+xI3drYjWFUIcAPk5Psd+rZSIyeHv2+B1Z6a+1I57mByEMKQyJALAEhu6sSDQHNIblckzj7akt2/X/g/81bw5TNFik1xnRbzNunlm316PURCRLHcljSsxF+zhlDGCe4LoD9FQOvlABASCCBNef5fcjCyANhggZfkcxksu+4h1ROWGWQIrAnz+5b11oOTnK7ViPbIU2TOx4KzF+ZAmbcRi+yADIW8mw1X+O3n4GYClO0GigyaJ15b8r1om5V4uOsdf+l1ZphO2GK+UDdhzwrdngeVcsByUmNkCrq9a9qQUY0lFvkRtIgzlDpZhYufSeVBYJsWhW2BO4LSJBKrsieekuOUY65jDnFmlbbk5ct7YpNfetK2fWXM7QJKP4+xz6EjI/DtXy3B8ZzgOSIlBqBuxy11FGKe3t00E51aFGSDSIZcy94XdIwTgzkFmt7UrmxmDZcqBaWPv1nIsj4THSS3xK2YhqgPnt57kK6GQ6l0CIMyrZFk5t1Bw="
    }
  }
}
