{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "./admins",
    "namespace": "default",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "./admins",
        "namespace": "default",
        "creationTimestamp": null
      },
      "data": null
    },
    "encryptedData": {
      "admins.txt": "AgALjrWiTyL7yhfx8ilJ5PxzAONR4D8H5eTcVzN/to2FRBAAFMGpMW7IhIBJYhsuWUd6sGKAsEtu8Fq9LNIh7pTg27uVk751ucGhaD6M08TpTSj1YzszkfINDMN7H4s7tyUs63Y3kfXTteET/DhkNBPK63v/k3rJ4MOG0IYlFk43XD/oGkyvCa3L0QhA7pNbDVAYpBA2HF/r7xRXCpMN+B935WMR/mdpinJ4TAbByiWrf5IoBqLLr4tMdUm803kao4W/IxH/mTeOiRdr5WJJlX7O4ixLf/+gALKkA7q1ZGeYq8ZZfk4qgEYZHXwA9XnmKC7b+5VAQu6jqiblNCU/6GVnT6ciUAcPmFv9g2n/I1uqecb8wU/bs1aQ8qOI82v+7NYbvXbT3x5qgD/XB2WvKpGDEi8mtaLcNCjhiDJOarnNZYkW9DCUraHYk0z226UgxoQs9HwCDP/5lAo041n01khzem+rRsyFwYXb0dtABgMhj3w7NJ32jEcpjsaKsIJ+fv5mxgIzlfYzeN2cUzm4WeRAJSduBVUTvTb3zH5xQGZLXsR4ECrKPObKsZWqZgHlLJttymW/olJuA2u8lo+pVtVQ4SYkNad/ajYcRjisw43hyZBTpdFwPAQdbwLlhbGOOgIqU77CNYy6QHrmPoGvScAOoNmEmqGVohVYkbaDLqGjRHmJT7r5JmYsME97tALoMfSKrXre+4jrm+B65tygKP0hB7na6eWPnnMHLuUvU5F+XEovTWZxmMfcS+eJbEiJBGW4oERqaVftCDSSZTgoVAmhMQgd4mfpXSuaKXQ6xyTCe5t6T0WoulD7WFYGnR+I6xi3qnhTmlQ5Yv0zZtmSoN9cwsOX5BtyJAclFgDdj3XFp+KegISnNybaAw2GRxSacvn4+AbJ/erFmAD/WZ5eWFz9bMZ/wBrdVbnP1bcDu6R7YcG3fSivQFWARrqrOBvtrO20tlB6ymH0G6+kdpBBRpVJNxb2GENWidgEcK/wZdR8/2i5E1Ia/KaaxL3YmUdFIEP+mjOMwkOygS9NQogNtDkdhwW0s9romiGGw61h8SesQWywDvilXi2TO/Wusr7hi2fXsrgXuo+7KCuQTw42fJH9hlbxCHxsFe19JLOodlqrz1jRJBMAMLR4PS+y+05+TAQuYmn+s2hot9MPPyWMwtmEZltvFAgvn1yp/PvIIp9lOJmhVL3oMLnJtUdcWwxklcLJP0GO++HVKzoiqusrpDv1/r1cU90yHeNdXA4m7vw/cM6onGVuiauyPtqtN4IyBVYsas6wSSxlBaHBbUxK7xElCSCtyxIcy2EsseUNPyR/s39Z0i1L31CU/wOFX9QxmEtVvoycdare90tTfX/KJotQet8dfm3pbDKkcC4Y4RN/0qZuj7hGh76Z0yoEQVHYlF/DTPPtZfyCq0KuhQ87+Nl1ZwFwO6jt+vrYaxqBJatu06mlGSAhqGS9d1Pr8rbQezfML/laYby/PkCRI8ZZGADtEFtUvek7Ux22pwQvsmiqi6MBQWES2OHtN7dKDd0B816el2bWWxe4mybL1rH6va1ZNxrOlTTZq0h37YTv0u4pxSFm6P7mCKqGYRyk+7Q362psSY2kkqVPf+jjOXhrm2cOSqS60Tl9biY+xdeAerOrsw4jkpZDrxQ="
    }
  }
}
