{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "./away_site_blacklist",
    "namespace": "default",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "./away_site_blacklist",
        "namespace": "default",
        "creationTimestamp": null
      },
      "data": null
    },
    "encryptedData": {
      "away_site_blacklist.txt": "AgDBqCTbJJKXYBiPh+mbgwbfxTyZZRC14kb5iycyKSLclPIn4EuMCNSe1HNr8OaX9fHx41HbZ6aFHOCUP2Xd4t9Zh/WyHeYF0E0hnwMDZPLhWqRMhWCf28QnLTZI1T3UUoaQ8oGn+B2j+skLmKRsAr5ONAFF8CcpEe8+xfavGgtV3AOZObMfMRIPorVF+MAybPIzhOSxeHcy3ue+yeaVCjPkpKgzCJMwu9YRl+u06jNJvVmtj/gSI8f377OIqa1hhk2o3rtQMYsCcavA/r0sBcl4ed0d3Otun7ng8b5m4bpWanKKKIxD2Fgm0Ccrhxl8hXoOKhynAI444pmueBjtoHlRundBJWU0C++xvBcuBXGtx7qNgmDsMnk58v3dw3CZJZEo+VVHdAf84vm9ISIz2oG8yZrmHdo92jl5k1fnrtX2syZa76j4myFq6R/ZqOf2+YFrGkiaA26WIHEXsPIruQo5mV/KA5EUjpy0wJnxYcqHnpXXrUPJhngKfOu7kPHB4qB/jpil5Y5+yjqykgb/8vxHqeIABeU5e5LXH73sWukgwXXn7p/TX9V3R74hGnVSiT+HcBNqQvyjtKeGx3r0tVC6kolshKjWcyhKJIhIv7wjawymYeXIgMsh+cmZyJSyyxFdqf0/On20qTxa427GyPgwq6Bfx7FvBFj31I3pqvl8H4PR0n83OKIRYLur3ORNFtoJUCiPnfNzGmmBqGphRGEemZctdP/V+jNwBZe1Hgh6jKbeJk5lM+Wak07lOZh4z6Bb+cOG+OuMQSKl76IcHqZ6f3NMaZQR3+OS4PuXgyMKmXU7eVd/6v4AXV5zeYHSYg8pDXNobxjWgRWpDzxry2ljFZRQjR/XKURvJgLddbKjfUoOMwsR0t0qnjWFtysINXgehuGP50Wiv/3/8qIjcOo5FOWmW81y+MJbNKOaFjLeGoa9iEZMjXxamp92JKz/YM1MhDNBvHX+S2jm0ccM6IuIRoMYnrE="
    }
  }
}
