{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "./banned_words",
    "namespace": "default",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "./banned_words",
        "namespace": "default",
        "creationTimestamp": null
      },
      "data": null
    },
    "encryptedData": {
      "banned_words.json": "AgC1O1teHZbMCvjCMgjsYn/pHFdEXUJDjDmJkOujlSNu4pUZug2OPmtCpVfijHpswVQqwbdgnSdjgJXF1ghQAiVQ+nOlAB2M8UnbyBwdpsJoXNyd0NtrRS983nlaSnYjr2+mzdbzCwMTvICyF1fb6/DuCbc416JVMA0EKHj/BwAJTf8tSmeMD8L9EGF+FpKsfvyq2jot2UaOaVVC3/FK2P2tX6l0JcMXVn92KVgQtA93ep/vsLgQUHUqzIcVvDaaYa7bxBotuwpqAtQwuefBVmfeXZD4eQGimfdLhaw5vdfsHkdq/mym8eMNAN3PfeUXwYn9uxN1G23FaTfd82iBX8BlMvUhCHANXFPHN/WpgK9x/vqDJtXKl8ZzF3Qo9kTPJfxmCL9iYecUFSfgj91yBumVwv8JX9zFCeAoPLqX9JCruQ1ecHmpog9Wv+dtOgDgECieReB7Dsk8uv3v13OYWP1qOUgKLyWwO1o6epFroTxj/9GQIXMfSTBDokcKHRvASUJrt5MddfLvYpglcJ9wxaVqZdk5v7jDcROInRbavMe5Be3etJwQtGHqwlnZV/3TcfJGKNrgRkneRwsBPum/LMtZLi23/bMx9urtqEN4Oy3aU3fuSvON42yE9n/SVveqGumzbRh0WB2BQHZnEfMeOmaSnCZAqYfGJXQ7lYz/BIxzO4Ncrh11xbFp2GVg4tRv8BotYJf3WGGtrSOvSp3hjak="
    }
  }
}
