{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "./exoplanet_ruin_blacklist",
    "namespace": "default",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "./exoplanet_ruin_blacklist",
        "namespace": "default",
        "creationTimestamp": null
      },
      "data": null
    },
    "encryptedData": {
      "exoplanet_ruin_blacklist.txt": "AgAQspEmiNBJB4f9P6LAYOJz79tqC5S0VS4dXvUa5Gxxhqkt2QqF0t7Amdu9n9EoO8kVoOq47W0rXexjWpQFaJ1PfqpWkkdgljtrwV6ges4bszBdhla+IGB6Jgts40/edSaIzL7j1kYAAGEANdBdRT2syDzVPp81NmOlZ3c7nrWkiRjY9ivzME3asgX/RnJqGpRgYdKKeoR5riB68elW9N94CALU6aDYqXls4OO1FWLFGji/XbRPYFy7xw5UF0jZfaf6HV9gPURi+zNfrtpCwHjlj4iNAdEZXEtik7zfbKXdU2hYgogc9OJoVsWr4r7dzMd+rrsgRuxKP4VcvqGphf88VoT1pLtI6RxjT8qRgzkP8jfHQSfdnNIJCaVW9F70J0SwDI0RBj2emqJQT2ji2+kIDG0b0+ITqXbEdLovMSDWE3DkXR7ARmF0jqUdymi9Ha736q7LSqWycx3nwi5n0mqOjRM5UUqDWdoEfDkjlk/kmM8Z1mgs/PvHBOriFaSFB6TszFqEnDs7Ehd7urbQ4mgo4CQBCJ0TvtcZqtJxMJIlcQhbrAbG6dEouKiwwr/qMjOUb4rfka9AsBvchQwJjkL14t3VxcrEPnOkkXY7F0HFIub9MnKEaH4Xn/KDpHBmKr4AriZ0ZFovbxC2RRLByuD7ta4ZfennDxfIRjI5w88KUpeS56qVs+3PIysqmY/v5Tdfhvw86v6cgcWKRTc6wvwnfgKpISz4lISzpH3fqnDDuf+2YEWBnmBMWUOWHBq0T+CtODZRSjlvYvMG4NlBCyJT92QUkPokxSoI6GdEr34cEOhM9TTIfQjvvM2tH1CM8fSn9pp39wu40XndE2CH3wFZYLElDH2GXijqyhMLJrg+3lPffO3iNsDs1WCOZM4uMuwB0Ex98JzZ7bOHRruUeuESbNyaPdPxn90YOy3WmKEpH+6BRORIjN+LLSUzdpRTZGWpwjFzgjK/I6XSsa5wmu03zkTTd4pmUMl8/A=="
    }
  }
}
