{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "./jobs",
    "namespace": "default",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "./jobs",
        "namespace": "default",
        "creationTimestamp": null
      },
      "data": null
    },
    "encryptedData": {
      "jobs.txt": "AgBRdz+LQ84saS9IPLZ6Ych4fCm8VvXn5nElIoC0Bt2OTylDSQrzUr4gImo7mWNu0nPMVhPFtvP9n4J0iEikKGQawVq0KsyWco2cvygBRf1fZ8rAoCNSW0eHC/Rm55JtrplS19gD/rFC19ekgDqdedf7co/TXChCATrMFiIEwQX8C9LkDt/IqosEmye5q6DsR3voPsnaUewT+u9Nm2M9KKOJ2D1eKIH67Ciou7WjRNpgawSdMb+q3aWYk6ZAtp/8jOSBFrpje8BGRqe6SMAFS9a+EYZizrgaF7/auFDple+ZC+KX34JiniYAdtK+r6cIHwZM+CaOoM5aVmhJnedpGseQdJDfu7xIiHbCeDv3aS/5QNzBALl/2itJZTn1v2rX1cbU6cqvVaQIBVTORwlQWJP8fSEyHXzsvZHrEFJ4qsEWDOKPh+/6PV1RnNOJhG8Z7IAwo8Gd+L+emVwQ4IavTMQ/xLCkfFOtPk1Wl97sr5nJu2flpqKB3RcN7jQYnIMtRDDkuQH7NVb4dbaiBqrDY6Qg9/3QKwZaAJJVXioVEdVioz/8c31jUslc/U2S2DSRzYX020WCfUjxUUm/ckIhlj8SbtlPFDBwLvlsgov6aQWXtqsyjA2qVrvXA1rlC2iFJrlKZqE1/TjGzFJzRvfNjKmw4CRjZ0HzvagNQgJzKQwRma/A80O/24lLX0j46EmThAMp5thtXC4KhbF1/nf0ao8hKEgsm25ZoUE6I5K5QW3ZM8GAVLcf9pLdwJL/flDCjXvsdTLnnOLpdq/CzevF3aYbmkpRITUe1V5Y3GKH9sGzVvhOSwr144wQQY+D5TJJL0e/BUhsxkwhofVW6qLMhA8GcPzcEioKkWQeQ6VFhDNtjxU8JjR6HVVT/EWhTl98hHtKyeMazlVC5Pr+oNCSxysBVS47kynYXHfWNVxTB2oqTtwesAKX+yFPiJOaEZk6z9cX61yginEe2qoi42LeNK4QDd0d7FgA+7pOS2Lug9NA9CogG1n8WGbjoRc5DgsX9FGM9GLCSsgykBRaLGEb8ERlWY/6zVIcZDzyX70XSR9wbj2/NO/U2W7Jy4oGqPCOYJktynadh253vCan4VjKB1nGDaW8W7SVpvOxfbR/tMvfAGJNI6goOBOvYCf2wsPPnT8JmWnOWYtyUEre7w5PSytZ1CMBWtv54mfmd378VkuX7dA0Flv0pjaIWZcn3XUtIXKewa+BKgJdMQDsu2aoHO1VsWcPSbxCuEd9GGRmY26zc8AM2ehtg8s9zPqkZ5XekbxEAO0kJ3bwWbSHza6p8cQqWXEinaEFLHKte3BGyX4="
    }
  }
}
