{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "./custom_sprites",
    "namespace": "default",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "./custom_sprites",
        "namespace": "default",
        "creationTimestamp": null
      },
      "data": null
    },
    "encryptedData": {
      "custom_sprites.txt": "AgCydW02qDfNx5ycHvXg5KTQvqWyIzyN1kX2H9ziD1nszxhOTdK2YTjI6DJgkSmFaQuJI/dKTbtfOgA8KnhkXpKbDctQqK7JQvMmF9+tUMkKYAqXEDwySNeYK7mOgbe1CO5O7ycXgY8DYtPR48Tz5RCmeQCoDXaenxtTpA2POEvZCd3OwKL0xsL5Y4EBTNHzZZhCNWVUD3di/5zKJzCQ77W9z3gwlvxEw8txXwCsE2zbtr0HoCjnPDa7TZ50kbg13V9Dxz/uZL/lnJK+Bm+UMrjoK99ZuIAWmY3r6epria0/cJsLlFMGLpPnr/7NTz7dBeY71rA8M7DawvQSsEFMvHOp+5tZFHMcL4DpUCJ4YJeB+924vLpdsOZEFHqP4jhsqB9PlHhNlBFUk9iNr31LEtxKx1P96sN4LpwTD/zIg1l9Xg2Fbx0yBLVWwtAyTruBJchTGZQtXw+Dc0w8K8l2n0nkM2N7BnSnf9nHrsrvMSMkFEan/zz9aCNjTV1i3Dt2bOuMryVUYvkgLSEB15fq6oDFu9b11JLguDKz/maSJTxzaO7V7Gyb1ayxmOCjqlDcHDPzd0vADUCQGl5ediDqU69X9hWJDAeB1O70UCAPiSTPn0pZSWtDZcQRdapwlVgTb2FZ5kWU62IiwKpIuzi3qQAyqJ/OYZTeSdgkyvaWX4cT67Phzo9lP9N25c73nVXFCj6Nuioanod03K2A"
    }
  }
}
