apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: foundryvtt
  name: foundryvtt
  namespace: foundryvtt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foundryvtt
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: foundryvtt
    spec:
      initContainers:
      - name: "remove-lost-found"
        image: "busybox:1.35.0"
        command: ["/bin/sh","-c"]
        args: ["mkdir -p /shared/Config && cp /config/* /shared/Config/"]
        volumeMounts:
         - name: config
           mountPath: "/config"
         - name: foundry-data
           mountPath: "/shared/Config"
      volumes:
      - name: config
        projected:
          sources:
          - secret:
              name: foundryvtt-license
          - configMap:
              name: foundryvtt-config
      - name: foundry-data
        persistentVolumeClaim:
          claimName: foundryvtt-pvc
      containers:
      - image: milkshak3/foundryvtt:10.286
        name: foundryvtt
        resources: {}
        volumeMounts:
        - name: foundry-data
          mountPath: "/app/foundrydata"
status: {}
