apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: foundryvtt-ingress
  namespace: foundryvtt
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: public
  rules:
  - http:
      paths:
      - path: /foundry
        pathType: Exact
        backend:
          service:
            name: foundryvtt
            port:
              number: 8000
