apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: foundryvtt-pvc
  namespace: foundryvtt
  labels:
    app: foundryvtt
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 25000M
