apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: foundryvtt
  name: foundryvtt
  namespace: foundryvtt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foundryvtt
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: foundryvtt
    spec:
      initContainers:
      - name: "remove-lost-found"
        image: "busybox:1.25.0"
        command: ["/bin/sh","-c"]
        args: ["cp /config/* /shared/"]
        volumeMounts:
         - name: config
           mountPath: "/config"
         - name: config-shared
           mountPath: "/shared"
      volumes:
      - name: config
        projected:
          sources:
          - secret:
              name: foundryvtt-license
          - configMap:
              name: foundryvtt-config
      - name: config-shared
        emptyDir: {}
      containers:
      - image: milkshak3/foundryvtt:10.286
        name: foundryvtt
        resources: {}
        volumeMounts:
        - name: config-shared
          mountPath: "/app/foundrydata/Config"
status: {}
