apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: foundryvtt
  name: foundryvtt
  namespace: foundryvtt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foundryvtt
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: foundryvtt
    spec:
      containers:
      - image: milkshak3/foundryvtt:latest
        name: foundryvtt
        resources: {}
status: {}
