apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: foundryvtt
  name: foundryvtt
  namespace: foundryvtt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foundryvtt
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: foundryvtt
    spec:
      volumes:
      - name: config
        projected:
          sources:
          - secret:
              name: foundryvtt-license
          - configMap:
              name: foundryvtt-config
      containers:
      - image: milkshak3/foundryvtt:10.286
        name: foundryvtt
        resources: {}
        volumeMounts:
        - name: config
          mountPath: "/app/foundrydata/Config"
status: {}
