apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vanillamc-pvc
  namespace: persistent-outreach
  labels:
    app: vanillamc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40000M
