apiVersion: v1
kind: Service
metadata:
  labels:
    app: vanillamc
  name: vanillamc
  namespace: prettypondmc
spec:
  ports:
  - name: 25565-25565
    port: 25565
    protocol: TCP
    targetPort: 25565
  selector:
    app: vanillamc
  type: ClusterIP
status:
  loadBalancer: {}
