apiVersion: v1
kind: Service
metadata:
  labels:
    app: mythic-docs
  name: mythic-docs
  namespace: mythic
spec:
  ports:
  - name: 5000-5000
    nodePort: 30011
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: mythic-docs
  type: NodePort
status:
  loadBalancer: {}
