apiVersion: v1
kind: Service
metadata:
  labels:
    app: mythic-docs
  name: mythic-docs
  namespace: mythic
spec:
  ports:
  - name: 30010-5000
    nodePort: 30010
    port: 30010
    protocol: TCP
    targetPort: 5000
  selector:
    app: mythic-docs
  type: NodePort
status:
  loadBalancer: {}
