apiVersion: v1
kind: Service
metadata:
  labels:
    app: frp-two
  name: frp-two-svc
  namespace: tunnels
spec:
  ports:
  - name: 31602-6000
    port: 31602
    nodePort: 31602
    protocol: TCP
    targetPort: 6000
  selector:
    app: frp-server
  type: NodePort
status:
  loadBalancer: {}
