apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: frp-np
  name: frp-np
  namespace: tunnels
spec:
  ports:
  - name: 30100-6000
    port: 30100
    protocol: TCP
    targetPort: 6000
  selector:
    app: frp-server
  type: NodePort
status:
  loadBalancer: {}
