apiVersion: v1
kind: Service
metadata:
  labels:
    app: bind9
  name: bind9-nodeport
  namespace: cluster-ops
spec:
  ports:
    - name: tls
      port: 53
      targetPort: 53
      nodePort: 53
      protocol: TCP
  selector:
    app: bind9
  type: NodePort
status:
  loadBalancer: {}
