apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ddclient
  name: ddclient
  namespace: cluster-ops
spec:
  containers:
  - image: linuxserver/ddclient:3.9.1
    name: ddclient
    resources: {}
    volumeMounts:
    - name: ddclient-conf
      mountPath: /config
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: ddclient-conf
          secret:
            secretName: ddclient-conf
status: {}
