apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ddclient
  name: ddclient
  namespace: cluster-ops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ddclient
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ddclient
    spec:
     containers:
     - image: linuxserver/ddclient:3.9.1
       name: ddclient
       resources: {}
       volumeMounts:
       - name: ddclient-conf
         mountPath: /config
     dnsPolicy: ClusterFirst
     restartPolicy: Always
     volumes:
     - name: ddclient-conf
       secret:
         secretName: ddclient-conf
status: {}
