---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: teleport
  namespace: cluster-ops
spec:
  interval: 5m0s
  url: https://charts.releases.teleport.dev
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: teleport-cluster
  namespace: cluster-ops
spec:
  interval: 5m
  chart:
    spec:
      chart: teleport-cluster
      version: '13.3.0'
      sourceRef:
        kind: HelmRepository
        name: teleport
        namespace: cluster-ops
      interval: 1m
  values:
    clusterName: oakland.milkshakes.cloud
    proxyListenerMode: multiplex
    acme: true
    acmeEmail: selling.milkshak3s@gmail.com
    # highAvailability:
    # certManager:
    #   enabled: true
    #   addCommonName: true
    #   issuerName: letsencrypt-production
    publicAddr: ["oakland.milkshakes.cloud:30020"]
    service:
      type: ClusterIP
