---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: teleport
  namespace: cluster-ops
spec:
  interval: 5m0s
  url: https://charts.releases.teleport.dev
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRelease
metadata:
  name: teleport-cluster
  namespace: cluster-ops
spec:
  interval: 5m0s
  chart: teleport-cluster
  reconcileStrategy: ChartVersion
  values:
    clusterName: oakland.milkshakes.cloud
    proxyListenerMode: multiplex
    acme: true
    acmeEmail: selling.milkshak3s@gmail.com
    publicAddr: ["oakland.milkshakes.cloud:30020"]
    service:
      type: NodePort
      ports:
        - name: tls
          port: 30020
          targetPort: 3080
          nodePort: 30020
          protocol: TCP
      selector:
        app: teleport
  sourceRef:
    kind: HelmRepository
    name: teleport
  version: '13.3.0'
