apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: teleport-cluster-les
  name: teleport-cluster-nodeport-les
  namespace: teleport-les
spec:
  ports:
    - name: tls
      port: 30022
      targetPort: 3080
      nodePort: 30022
      protocol: TCP
  selector:
    app.kubernetes.io/component: proxy
    app.kubernetes.io/instance: teleport-cluster
    app.kubernetes.io/name: teleport-cluster-les
  type: NodePort
status:
  loadBalancer: {}
