---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: teleport
  namespace: teleport-cluster
spec:
  interval: 5m0s
  url: https://charts.releases.teleport.dev
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: teleport-cluster
  namespace: teleport-cluster
spec:
  interval: 5m
  chart:
    spec:
      chart: teleport-cluster
      version: '14.3.3'
      sourceRef:
        kind: HelmRepository
        name: teleport
        namespace: teleport-cluster
      interval: 1m
  values:
    clusterName: teleport.milkshakes.cloud
    acme: true
    acmeEmail: selling.milkshak3s@gmail.com
    # highAvailability:
    # certManager:
    #   enabled: true
    #   addCommonName: true
    #   issuerName: letsencrypt-production
