---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: sealed-secrets
  namespace: flux-system
spec:
  interval: 60m0s
  url: https://bitnami-labs.github.io/sealed-secrets
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: sealed-secrets-controller
  namespace: flux-system
spec:
  interval: 60m
  chart:
    spec:
      chart: sealed-secrets
      version: ">=1.15.0-0"
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
      interval: 12h
  values:
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000
