apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nebula
  name: nebula
  namespace: persistent-outreach-dev
spec:
  ports:
  - name: 8001-8002
    nodePort: 8002
    port: 8002
    protocol: TCP
    targetPort: 8001
  selector:
    app: nebula
  type: NodePort
status:
  loadBalancer: {}
