apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: turbo-mumble
  name: turbo-mumble
  namespace: turbo-mbl
spec:
  ports:
  - name: 65738-65738
    nodePort: 65738
    port: 65738
    protocol: TCP
    targetPort: 65738
  - name: 9987-9987-udp
    nodePort: 65738
    port: 65738
    protocol: UDP
    targetPort: 65738
  selector:
    app: turbo-mumble
  type: NodePort
status:
  loadBalancer: {}
