apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: turbo-mumble
  name: turbo-mumble
  namespace: turbo-mbl
spec:
  ports:
  - name: 64738-39000
    nodePort: 39000
    port: 64738
    protocol: TCP
    targetPort: 64738
  - name: 64738-39000-udp
    nodePort: 39000
    port: 64738
    protocol: UDP
    targetPort: 64738
  selector:
    app: turbo-mumble
  type: NodePort
status:
  loadBalancer: {}
