apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: turbo-mumble-pvc
  namespace: turbo-mbl
  labels:
    app: turbo-mumble
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1000M
