{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "exoplanet-ruin-blacklist",
    "namespace": "persistent-outreach",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "exoplanet-ruin-blacklist",
        "namespace": "persistent-outreach",
        "creationTimestamp": null
      },
      "data": null
    },
    "encryptedData": {
      "exoplanet_ruin_blacklist.txt": "AgARwh/OpSZSZ66RLBkCq5pVAlX6ZepjVwA2pbe7e6woAMDY1o2FgPxmFCeG8z2fpn5eVAwo9kCkCHZPkZNAf/pSAqC4vXpceLgHKnJXMbwgUaj2HpmrO+WIIrJ+/rbgW8hQERdIDYqFD+3EEKXIDL6cvTjLqt5ZIUN3zYVAWlL7655FXUCK84KGvFdR7VXdQvR6UZRXdehYCE5klR59ZLBlzZpJGX8Sr4XmneAbuRfSey4Knbds6BWnNEt5z+RtoYPdGkfnleRL4EUy0BLX+S0nhy3uJ56FZdjM1E9sIuskNrNKVAeFgV+m0DfPL0Cjt8iScNoIkc45Xcpi7N1XnEQRgzvJPux26PKbgmRTRRaal9hc9Wn8Rb9aSdsg/mZVZZLcwkdzmIe/zJNsxkr1ilMIIfqNuDdDMAq5Ftds/4oFlw7TCeftBfpL+kWbXK8BckmypXZRdskg113RdxxaYX2Luf6cS3Pt3dTnWBQBeagfnAPpQ99HtdfXviqba5/lQSmaCBf307I1Ae3sI+LOFKdZWK+M+rcQGrdSWJlE/BoVRm5wxKxS296HTZWgBULTxeOykQv0PsTuQxEkc4HR3dsQehwy/FaWnbOaac2FJXSiqRsMd/WgA7cWX97h2b2kJpbfj0ZCBUGMeZtPuxNpyvGA0dSnE2XUOfz3kP5wkXQMMKaTlTbirf6JNLdrMgs+ldbmFfOYKdeWI8BGaRRdYUMbYcoSjGmrNz4o6uI/cEZhVQPd5VsCOnrvzFXUhZ154vJhrBBzKyAYCs3A8+umTJ3URXlvwM2ne/f/2ytgG+5IYtYJliIikc4L1dOJ4WaiVwv7FVyD+Y/vRrupEvyTF62aw3aU6kRijLEnZnShtd2morLogDs+F6YCaCfdMbCHWaU/yNls5e8x1nlY4r+7oMEo9Jq/f3nv7X8KACfqV5+Y1lM68UhJfTovkLyVcWidi+wNdpp+t8LubrOTn0r8wliHYSXz25hlJQ7sWQ=="
    }
  }
}
