{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "alienwhitelist",
    "namespace": "persistent-outreach",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "alienwhitelist",
        "namespace": "persistent-outreach",
        "creationTimestamp": null
      },
      "data": null
    },
    "encryptedData": {
      "alienwhitelist.txt": "AgBTtq8LxLH1ceZERdml8umEaU5zpcolmmiWwQgE4tyJ2zj+MzQtwlM28ANc81Poy1Gi1hbuxoW4DRyGs4yLUvcU7m21YUzvLk+Uao7no3ocavJzUA26OYp+/xY1YZrF7vPYLsjU5/gWrVeCcjA8xUnQeRLh04aY1UBadegp9VWuAajna0lrXmYr3qzvHPV4hB3wNa7LEw4+OpZ2YXq1LGdgIc9F5UXBgZjUmIcZF+b27+BxAq2bpqfKTLdUDtL/U57W+jzYSMEerNCL+levf3E4VAv3TTxopoSEVqNCWjB62DdOdlbgi5kn07SK83TjuXHhXNDZWm5LZfraGfZvZvThyUIFFEza9xm1b4gcxima+q0eIVH81Ajws3jUMixY6ceCMCml2fbHC5//wXcgUpLz5h2i15DeId/3ZBtvqeolUo9yyujVoK5Z0JO2mkuP70wzwFWby0nsyqpOFsC/YyuxJ54dQPY7i+4TVsMe3CuVwVCzGfzl3TSKCkGnPcqLrlsGE6HDqPhww9RwICs7w+1HpMPFY+8RhBP5Oh7FSzkEYQqQfhpl495L6ryfcykwmdBXRhaaSzZGgOivNxzaTSAguX5yxe+OEAW+0BghSqvpwnO9Xm1CJe4/buVeVo2WamAI84z3nJKxSIRG23ivwUonaVb1GWRkGtTHK5BAP4GxRIauEPJPzJOcXAbX46gCXn/dTf90EKrmclr+7B4gcqE6oAGy"
    }
  }
}
