{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "moderators",
    "namespace": "persistent-outreach",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "moderators",
        "namespace": "persistent-outreach",
        "creationTimestamp": null
      },
      "data": null
    },
    "encryptedData": {
      "moderators.txt": "AgBtFxPwaJDJcuQSyPGGtDO93brrbQcgTr0qWGf9hPSAoJra0wjDHH9JKEFPKNH4HJwNuLC/hRiZE0nv7GdP2+TAJyy5iei0C0dvhseF0L3JQKNVx2161SeHBqHG2d9S/NhU5Lato6PYN0OIDe8jnIwZQr7XypNrM/NFbEJ1I8stPu0Nef5tjJXCOscDOT1+xiyiMcOlpHEyYSZUG7P1bILf3sf9slE64opPAerbl/kOvx2b9y/sAvSnQS5ZF+IEKB73nkibB8WXuYImIncYT6oXqPkA1GBBKfcRL/pWVZwk4HWTG8jGt91eIhGKMT+8jxeJ7Esn5ldguEaxABgNavAxgLVsqeMWLerd0rPJiB6QPHVoyRCOy1XdcasX8q30vsj8+nBeiwNS5HrgM3PgGA0nI18j2GHEUvsME/YK6wai+ZjdRd/zaao9kuS0z9+3Juxtzj02yosX0D3LLZJq+tSLIHbsClIWWXNWL5cLw35DsxLT/6vLNsHC6gf/36ZWWrjLNzzy3ehCNY8qp1UDtNLWuWalE1ke5QqnBltIkA9yuQ/TMpiloGBeo2wpuJZiqQUz6wgAiIJM9NmFzeMqfai0nJoBCf83SDIFPhn6+FTsEXRFxSciFiTTUo08lwhpDxrW3HMO8mB0DbzSWw1/mJAXyLgw43LGKBJKts3oV8UjOhQCtKN3mLb9GOJUFJCFw/B6C+Ueuo7YTXxya9kGvggAqVygA125xoPbfRwJEFYnlHOO17680aJjUSrceObqfrzHoXiGRlmMvLkCNfi8hTdbo+MmDf1DKAyPRwjIzsiaVeluSADdCmAKVyj9gs3Amf/VOSoeKf/BWkxib8AQ5h6I/bj5LGbve7w3bK8UpU3nqA=="
    }
  }
}
