{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "exoplanet_ruin_blacklist",
    "namespace": "persistent-outreach",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "exoplanet_ruin_blacklist",
        "namespace": "persistent-outreach",
        "creationTimestamp": null
      },
      "data": null
    },
    "encryptedData": {
      "exoplanet_ruin_blacklist.txt": "AgBw5QMeM5ZqsR8teg2+AMi0EYjRzA2C9ZfGVoWXjNQ/FXguGfcHl2cNgjnCVmPjE7/1eURn1BNCMEXoUzmPnAttUbJ1bpUXiOD60JqCW6qVHQJGRGKr22YgXChZBvqo4S3avef1hCc/xGuumwQApJhMrATooUkVhk9yKxNaesOEyCM3dZ6oHYUzRekKxzR7y0y4d/r935/TNxExaS8E41VnlbsSEfanNBl3heQ989z/PFAfXQLb35e8KRinc85JtKuqwRF6o+S9oER7uiL/pccJJa+Ls/MteScK8n73qOucAUEmDjD5ZQ/dygPlm9TTNmG/SFwgeyCemHeAE3/H9M1tZPjUIW6nqNDhzmKSZGtD+11COT1jmVwEHpo+h1hCSzHZIAI11oWcTV1wSkG0cOKyLmv1CEpm0pYVHZl90f6kPKKNqJtiMhBEjZazGgvAHe6yTRl/DX2ZeimyAp2WYWVKsvub9h6I9LCSg1zPnwCK6xlkGWlYxLSvd4Q/6jCoDaFyjZLTPRAPztq9I7cmBtW0GewU2gbppbUNEKDGcTGbkcOhiyQZsN7aQJy1MEfVRBC6yEmQ6QmCHLcZMAYQ+hzD+zk1Uoo/Oynu8YSvmweaAJ2HxunIxcsSUvgXYQpwHf3T8F4P+EkZmDo8sj8FSXocESKmMyzPcACRmaFoHVuG1K9VYjf+SUZWeD45JIxDscsXZC/4/DItxybZNC4BFU2nj/K2dJHiGqPfzYNphsyCW60rZ5WrPleF+VvqSPWtogb67mKn3py3cRsWLUb4xafNidJWrLUItB1If5PiXdvZj+D+DAhA0lvZrKNmkLUr1doT6IGYChFeJQeo66amDlvUj+fe6ph6BZS24wdAegVlG0SSP/nsriGPuX4dZVf5V65OLRMSmpsMMJg+QqpU94ipljpnemwzj1hOQbbwYO8KTkIo0v7W/5fN2DWefFVDnIlgTaL6XFxYItYpdoTEVq13YMTH8kbBSRiJeA=="
    }
  }
}
