{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "moderators",
    "namespace": "persistent-outreach",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "moderators",
        "namespace": "persistent-outreach",
        "creationTimestamp": null
      },
      "data": null
    },
    "encryptedData": {
      "moderators.txt": "AgC2qc1JO/64KoXfqZ3UNej9cjts3ODrWH8fS/PnXUQ1hcoS5qOowWWGYtnwe+TskfRY6xCm9dmQFnLsNlCbkjbxCTJHwqqDNF3P2Enkr/xAJHAE41+dJDGQEkjIs5K40Ss/ZJY+VzdNlcOp5yc+3McLPZ7iMJULLd91rG09oLlwITzh3iYf9Sfed/1aePRsBtjlFf+c2fqIHnV/42Ck91FBkcJjQyz4iNRF2MukIksQzINNIBxgxf8+YZc1JA4v7pJQahcXNASPO5ZFiDFX3t1rQmIH+uCuzPEb7mFxhP4IuDBsHASX59mPlQU5AAN09bMzxxz8rXmjsOPKBjh0rJ23mjkgzttNYv3boYCu+M/czaOFH1HUhCa9sy2KwMkSTJ8P5S/JrbVLyOVIS3eOD1tkxEXrfSGHO5juBjicyLQmrkS1Z1wQu06n/55RZiOQKxV0fuNrz9mHBMQUFviiL23Ws15IgbKhuuRgWOZrYt6KM4zlX8ZFkLTiO0RYLJvWJK4gC076NaeF+oGukS1jXuR6toc0zGC5w8joPxMFo9HmbhJ3MIasuT5etL+wvFdI4WbsJ6+hGG/PkoL1Cj6QAE1GQwj5VdEecVGID/FknE/3ZjD6u+bLi8B30+vtr4ZqW8VwjlmXxamjSBjp/ZGGGJgbsCuions9ztfKFFbXjjQvsLM6OhRfpbnBNVT+GrVUpajYHCi/SaYakwMlwRaFLlgEsm76zaZzMB9eNM8pjN1nd5CzdQzLC/HXTmeXmH7Qu0s8HRvfRBkAf3vGWCCbCgi08vBjNHc7bF4iBVlxP6fmNXFEH9ZhGLOx3C9XA45+hZClXcX6W0iEacL8KmxViY2IZRQC+anvu1LECyoRHNt8XA=="
    }
  }
}
