{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "webhooks",
    "namespace": "persistent-outreach",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "webhooks",
        "namespace": "persistent-outreach",
        "creationTimestamp": null
      },
      "data": null
    },
    "encryptedData": {
      "webhooks.json": "AgB2ehkTpreScTJXgHJ9QdvRkeuzIrOBb79KO9DAEHtvKd+fhTvw07E5EW2BEBtJeOJhwIW/sMOyGnGb/ofSsOoBy1aa5bl6NmkrcsYsRSJEnnFUPUQwR71Po7o9ymJS0kl5dCAeSsokDtTB64obAG7K9tzYI/NCES/fGjNDIZEfwoRE5Wm8/vBy0IGVpM2Ol+oTihmJBFa7q0l8juTwAe9Q+QO1KIQnfovjubzGrgvwaH6cCvWR744J+cXpHHN9LO4zystzgWs4IYAWCkvm6gcBJiKFPM+BRn68LNd1dqbeTO88YAqrtYpdK982ZV2j3tRMEUCbl2YvZrDP002Bc0Wh+jGCL9ZflErElLW6CnJ65jP8N+aaGjbnLuMGjlByNPNPARGy2nm8XTc1jYHIhQSZYamssXwBpslZRxgyCuQO7Dk5ExXw1qNq8yJil1yCHwmuZviOXOTZKERHjeIveM2GNJdEDGR3p8Fy1fP7d+JgUz7k62eU6ywZxzb2TZbms0RVd3F70Wjxqx6QGbn00eeRivyYUFdnckFZOePSNNvwN0TZICJCWmqdfU8bxgIAO6rLPNYbrz7xYfLMv1b+05VJxvIFlrjP6SfmCpX+6JJR06FB9v3VncEprX5Yv/8j2BePD+b5+t82SQ6RAtcm8HizkR6BB6DslLsAlYElR0/hTTgzCc7CC8AMWEhMeJvOq3fQygk+bB+FtvyUGgMkJ77QBIhJKfLJ/cToJ+MoZkSxWUR9JRenUVZVmtufUefxRr5flPIuDDcxsxsWu1c0ifzojsxEXstf0ngXYdTUF3OXsjazeq6ye4nSBpRRjUmuWf5nc/9fPPvKXnH0onU7mTVh6qLhmy9IgsQh+DdXfaEoevvipHvtmxB+IR1XgwzpC1WQq9Egs/xnsgTzAXga6vGvcswktEvJbbeXChMRumQEQjRNPfDx4N+cnMqTTEZ0PXgc+q78475ZhLiYMjwfNB5kf7JgCpMBbpD7eYLQ8xMhpte+s9Iyl7s="
    }
  }
}
