{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "banned_words",
    "namespace": "persistent-outreach",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "banned_words",
        "namespace": "persistent-outreach",
        "creationTimestamp": null
      },
      "data": null
    },
    "encryptedData": {
      "banned_words.json": "AgBulePOoh2b9c0Zbds6lmVolGjKrdR8nA84iF5qCiNdDycI1vrDm2jWmS8MDZLStTbtgBmFEk/EYmAFxx2wcd2HUg2Vo8rAfo/M4Ro8nodlvv9ClPKsiajBVXD6mza5+c7iHj6k/BY31xBxwqlAgt2uYdr+TCZKeZ4vXI22NB2HdWGs8cqFp1Yi0ETieBPfTVT7p+B6xVJxmZ6eBtdOlTaEGv0oLbwTtYUeA6MuG9FKUhgDFCpFJwl7EEdSOK5tVN8E7RIdGBp3vo+nnIyVsX9JUHSMoDthXD6u8xNQofo3KKEGO/2ZeNtqmWIHPN2wFU33j5224XKZq+ZCcnkM7ssTxRADpCs3jhks3MNIOBpafHA10uvE5GArfyJjW4gxPaU1j+xILBFwwK3lefq3xQPaCrefFCsBI57Q5Gakdv/kIVsmoXNk5MEP4+MdKVD3tMWnlqppGC/9v67T7i0c9fWGflXbnqrmdo6xctPqGaRBYklQ8KuPfDarrQ4IZKA7fRuRfUaXx97YUXqW0Dl4hVxS+s+PQQkBuuKDowVRDpHVYpEN22nba8eYPOrWqRuz5+w3F9lAiDcSOIoTZ82K4NxlcrNh3QBL2bRMLRu8rNj7hdsUU3+uSPKPlGCichF2cC/1bRlv7jvb1padqqB7P6xeeRPylrwEdwWul8xKJ3WZwbROTDBwi1/hXVd+ytCZrGxjXDtkHXm/ZiEFThQ/AtM="
    }
  }
}
