{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "custom_sprites",
    "namespace": "persistent-outreach",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "custom_sprites",
        "namespace": "persistent-outreach",
        "creationTimestamp": null
      },
      "data": null
    },
    "encryptedData": {
      "custom_sprites.txt": "AgB8iEUCUZnQGa/fQED7uooxEgmoP2HqKdLE24H2YIZPPEwBb6xrgDR3PQ17cf8sd/x8JBbIC882Y4eQnW8sVVJkE9XhHVgBZc2Ex9/ZqIiuK8nVG3UUc3Jkqf/rTZutd8tcMMSjA1Cax8k7TFIv0V7mHpMpmnFw/07xRxvFCmvtfuHms8GVrA65zAOEeHmjcWTIVdpVtyHo6d4RV6Uy6/8gXiRUarPVM9i1R+qzbbDuupuNlCBds7VpIcAm9fPbZI/WNUnm0Egl9cDGcHqEW/9jeRTLVhUoV2mywVouFphSNe4lweeAfu0/s4mUvgu5pc2AGpRuEuUlENx1OVKswJbxLBDtgzFqqsBrA2npmdZxqSIj300Z0m3BJtQbZT4nuy0hI+LleMIZ1qDoOlLJCN/ThaVSJ9tIBbyDusDz238eVS2JZhQ/aX2Sk88BGD5AA5ggvnpL/yhdfk+jNlLpCdJmzT5JkPMl0yd+94xygSuVDqZw/6fEvdYMYnwYI2L0jqdcNGtgA4kvPBT+gtMF7YWgpCVES/b02h1ANdmep9hJTXwByfdmBDUJsWiqJdqvZIODB2A7/EeN5BhS5DqywYetBXXf+vYlWyKq2afEFqmZbpIrUmhs/kmQuRVNhalCi8ogwuOmzue/qhX83nHnJZfqmKvtEfBT3lv8AO9GXSmdbBdPmdzcOcPZaQFg8OzitrtOade9NwLrfk9X"
    }
  }
}
