{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "dbconfig",
    "namespace": "persistent-outreach",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "dbconfig",
        "namespace": "persistent-outreach",
        "creationTimestamp": null
      },
      "data": null
    },
    "encryptedData": {
      "dbconfig.txt": "AgAmBNg85RHN4l+fmPh4zdx7wg9BYDh3FzHHTsStZfH/13vlsf8txF3KXijt8QFCXUjnfUJkNOZG7GXuCT7gikwjheKwCxAVJI5rywjLbiwFSjC12GfwA5QJshsVY3RTnqHUO++wCPVMHQRKHA64fG3E3cmls4DGCF55wkLgr52V1HdcxnZuiaurD30gvNuBfpUnD4lg4KZhm5X4kYzX7cFREfADqa9jekkHxY7yly/BDmTALDUrGZTkreNtOntnnSmRAwRuCXNQqpVc9f4v2iJ9PqcF11lFyZfAH0ktCCpetps8xKY8/YZ9m/lSFSLzd0RxVquYxaZkfg57ndQmy0c2aY1YJ8lSAbOzYOcDv6oknjhHpHNXby+qbRUpuG+Jdj6w7hhVYKs7lmmj7RY5h8wHwqwKlKfzj2e0sKJgIz5rFuPPPPftOKgxr6DHxATL0Fej5jz6vb+pcRVZ2Ao6zOHz18YDB2u9OaPswMVrqefvGD7fo0/9Oex20AMHlcP9rml5OXw1P0uWRaKYqhqQx/evjDXwturLspbqXX5YhbB0C/0DL7E9yCl8CJU1BkEjVQkzu8XEEOUWRSCMzDKwYNquel++eertqB8WhSOSJrT1dqy1d98kHcFnpAyoIpWkys2zaIhBuE6urEhJodncy5jyxQ+r5qGaox3SQeHBIRmTFPyWtX9u9yAVLDpGanizcQf0ywWeXdLrY2+dBgdm9YSoknw3YPgKN3srxEczGb1g3VGMkZTxYJ93H9VUAFoHbsjjnDEuqHHlWSvYRD4JiFZDvGmAszX4Zg2YhKvdzMXq44oYME/UP2fTMT9CTYO1ydwATYVQcalnfET9flxVD2X96FSIsZNXAu1M0kZcDxFow6GGbrKwAtzpBI6E69UHyZapjwm6zo1UtQDGrd7vK/7o5rfju/LFkfD0opoh4tRKs/3pR7Km+I7+N0diQtAPIbVHOT5TLzEfk4zqVD+4KaHb5jIQLHBnaIuuEMf3Mzr3mvWzTkEEYjW/xq6xYoE02wppA/K/82qxoYs6LuEMz7HMxPzsgZqD5w31djo8GJQeioyLylq1cBaYWXsAuNnPCIfpXs5NXXHqqsSzxXhErQciE52TFQS/rKUgEguVFGoLge8O1Hw8dbOu00b5MqcPQav1J874qOyytkklvCT5v/z8aiLj6P78eTgb+CrxfxPOmbEEmrXPSWiG99jZckG8QIoQoyJ2x/gsPKtlOYjMmnPtrg0vqNTc9EdpzqOatq5mZDfY4x42erz25ET8eFZlQCb24t5Xt21vdyc8Sb4N3dpfMOPnWH86/wDokdRkS/cx1g7T2Sy6aoUtvcfExuIix0MLkTc1BJ8yCyJw8j8G6HkGLQrKLK9VmVEv+jEO31YvFUzNGToBPYKDubwLlH23nm3viEYvFU10Trvd3mjQXu0aJx4SIQuqRuwBy4qePjLDDN7NDkOoJV7oXx80Tw72t+ylp3y981KAT77A2eJ0xqUuC/ndXETrpZshjUYSf+luVehCm9e0WhOdRw4ZmZT9JWISd9UhRqLfzVPgbPFw5ddZXcyehnLUWRQGz4Hg064Ar7ADfdLTlTZjJ57Advt1G5esOLAQ6OP8YBHn6+eun4RT8xRDxEKYvp50mzDJj/N3dUGlVB2bRymYY+4hFQ5D9gcY5+UU97h04Zid3OGHNpwagRh44Y3xsyEsefXhXuFyU81zFRiJS8D5jg=="
    }
  }
}
