{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "alienwhitelist",
    "namespace": "persistent-outreach",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "alienwhitelist",
        "namespace": "persistent-outreach",
        "creationTimestamp": null
      },
      "data": null
    },
    "encryptedData": {
      "alienwhitelist.txt": "AgBVayBIwDyE6pVv6J6fKckig5gqkpjC8HuU3Wp8HW0Faf63eFkcy4rCxDyPONibFyA/HXWmkSTGA0CifqvmEdkCminyPHrk6YaAIRfbFoqiGh83mfo/W+AU6ViQicB5/IiX/+nYp9swoRhzXY6JpMXAAA/6c0gui4uOHoEUCFZhBmwdyRF/LLQGWNJ88cJIEPH8lKKLes6VQGw0zIeRp64dkJmJ+qTUh5effp3fESfuvC6FKRzSqmDbTES6ZcXd3tnmxaRyQnxYq2eIiHzYbH3OFX27vDQ7u+tO6p2qrEHfWv24H5JLSAaybuPem2eV2mUp4VDHY7wGk+t4RVtUZ4r7eUyv8r39Bc8f2/Ift/eCC6bNrh/j2vN0HE0gt7LhYq1veL62PE7J/BTI8oh09Hf/uKBvXquIjiraYY5FF+PHNDCEXl+Q6RrRLp0t9UO3PtpI2kpvfgoQlvs94UG3o0c1IuSRrc0CSkp6uS3JYJC5vyrNBD6XHANn1n8xc+cifdy15weuoFx16KJid9DFnYMA9nb+m5AyTGrSztrYLSZ9RVjHveIlr8k9p49Y1/5rWR9v86XzfhqNBMUEMr6ApS4UpYCuq49rS4KNVKyfM+WIPhW8WttRyymfEvUTqojnvymQGhapyLO+EReGuIutcZDGs+WyT26RDvTTVLOJThPCDi+J6r2XW58ujreWCG1t3PMbnojmp35ZTCH7HyXecjslgwFt"
    }
  }
}
