{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "dbconfig",
    "namespace": "persistent-outreach",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "dbconfig",
        "namespace": "persistent-outreach",
        "creationTimestamp": null
      },
      "data": null
    },
    "encryptedData": {
      "dbconfig.txt": "AgCEJVRYunaSm5z2/X5qRX1ynU3GbfgCakJv8UyqOE5Z08iWVDCWAQPSVSzTt/3qCWDRobDGAoA5PINVXQC2G6+EntVVBDV7FJrVTf5F/k7FDzIYDPc4iclGm2uYAVJD8a0UA09iu0OJv0kaQrMHZRRIEtJSLr3pEsRT/KS1olxFUm+qQJjl8MSg0jhbW1QUl1naN3dAcMF/Pyp6WV6O/+SqXLTdaxNE57V5vg51L01uV+bruFSx4b4eeAMuXROrF/+7Umf7t+/PikdtiY1yB8TDB68Ors5yQG7d8JecrNtsg1ffxD1byrKsBXlkgvZIHEH861f0F+IqEmzZtv3Gk/K7JxfwRf1fl2NqZR9089XQBJublhGo6TPsGfXiGLudFiMPAND7eEacW7UWMc59hc6u/KFkS+zp48EPA1wxIFUzGiwTuPWniHWpXY2tAufB2BMD9yRmMX0T1ifHKEsGYNf+TSCI0h45eXO5LKXYnAMWW7ZRt6lUhqBlvBJZ8DuX596voCsApQorzwRkwfAMZF6Ove5HVt5NmSWCd9NeLGirRW5fNgQW3SEkx5xWhun0/FOovWHWlKgmaa2xdtE7QFHto2dDTeO/5Ty5NRAi/j4MKy16P2EwjkkWrOQ13h0MePdJ8rPDIy+pX1HGFV1EL0qv5wKp170UvRzwU9X3AI/73BX7h9s5WiXTKdHJ9RXBNE7hY1iG60xkmS+XQ6vFbHdC6i+iwFREkFXn0PvvlfR71iq+EO7KMxLq05bSZ0O8HeVRMm8LTNWUupPNz7UNh28HrJqzhZy5Izb9r1xizDe5jixbRqYEOqwAv+cy2yrLN+cEgiFDTzX+OTQrdEBZ1GpxcRScjTHyvk6R5wKRCLP40rgPYpYGFpFJR1VGTehBcESsXj0/jMeCdOq21L1WKbk0++3IX7BjcYZKEvEMmbT3Y9DOvb1rhFfGV7sUkBdUsPhoXsLPTgmUCJhMqKuaZahOMNDMapAh5YFh/0079bNlohljXThr9pjewK5qkDYx6xODrBDc8XCZ4nl+DBKgToAF3IZ2+TrgywgjSP6404yu2e2XT0InAMjOiI5CbtXptZGlMm3GOEEwXmTpu7dKdte6MGQzRBuMxzUZ40SIs3m+JyO9sYUZMbTWnyP1+tXZGlwCqkwXhb+tdZLGHgI2wjT7Bn8OLSyo1MCBACEcTzotW93nm4O6BGQfzGPQcpo8Ivu8a+YG0KnYswwY3MvQsvySpPUZyFiCBmXlF86H4wZrToc5HMBzLlnsdSE1Piz+rd4bme8BkRrAARJTNXZIZU+BMnNU6h7mKAfhTcsWVMUOUGr4poYwR/DRhiTtqfuHYw2WTa6ATtTsq/5gqY1y39jAN7qswjZjc1W3Fxb3ERY5hozleHZCl0vw79YBpskjZFj0KPbxx0tUW8n6dkeylFIKW9LjJEOazCnABFYS0ZE9guukUMeAkmFPl4G2cFQxLAY87av2Wnw++7QvGLC26QRrNaSwxMKlzZa1iuTzSoRILYpGvz0Evp/mHyZPTDcW/7liztTHxw+yIZf7ae47BKEfwW9e9gtpglz1+P1mMHSYAP8Zz8gtQ7I57aShxjilt0029+EukKc0UG+3l94kYxolfLStIcYblDdGYsebGcZhSEtiX9xcjdrNIJCZXNMz2NBxSmLWIkYOKs4PHFtPddB3fPPpxS7RWmj10xWt0T32di7lbSDOnQS7uA=="
    }
  }
}
