{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "motd",
    "namespace": "persistent-outreach",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "motd",
        "namespace": "persistent-outreach",
        "creationTimestamp": null
      },
      "data": null
    },
    "encryptedData": {
      "motd.txt": "AgDlW+OeU3fsurQ4Cb+2ZmfvRhMdIm94EQ1a5nvtJ1598hrf0iBgpX4cEi3WMbkC6nd2ECpIOj0upmpCa4k5KKkTOflmiOtaTdF83sOTgXVydFV2jdGRcWArSr85jGxgByc95wTOmmxm45BVo0nEIBzSePY2AdL0k1v1su5jQ3HC6Ss8WJiElvSI6m5RBCbs7XsswFi0CdLuw0tsQZzyPzWwJSJ4+G8X0XV6AImTe7azf37eY1dyxrr7dbgOCp7MtCy+4X16nXudiuAg8UdA99c10KD8bD+HrFYR53bmChitf79Orjm85tLNb2Zp/s209fNX70Gabhv5BnAHpzW7AeJHLc0rkUA70V9L9PpzJXuoQJ/RhVxlAZ4lLm9t4dSq08gAeC55cf95sb9rAw6CVXivmiwazfSBcG3BTPgHvam6QAuN/DGsrDNOTx8mONbvXPFxvAGEeaKhdCLrYYbddP4wT8kGCN1avqAR3p2CLlBGqLZghIpJHE1gg3Zr728WVfZSzKWaQ/S3+lk7TLQgJK8s7qHj9BqlTjG6QY/L9V0xa8CT4Xs2q+OIbKabBx9ta1KU/umRb4babr5up3E4Hg63szpLgeXoTl7SzNbiAjc11Yftou1tFcUvKL8VVdXWqgtmnVpqwBEl/9l9HANHyCydmwzODhhMdShhqWmO8YzGbKEhLnjchfkSlz20RlhLBZEPrOFWlDoCTn0DftgkDFB258BcFyNhpn3DATF4hI9eVUzsslWC9ea57dSxBhtOszGLSGTJXoX+Vzv1JA39muy9L+OGXoji5eEmgQaE/V3+cLR/Jt/tj0a08dWnmk/MKuJ5GhacIbvSlIXnt2QhnfjZ/nUDO1/A8hWp6a7XqFBKq7LVQfB3n2gNcUZ95H+cBirrtW4zlOhM/ASWsQyuEphu/qZw5kakTSOI6Blw166SHwL/pS/tsWRIa0aDvmk1NTnDb29UcZN+oTi5TkKw+kb9vG1xtWkF7VhmMIY/CDM73Fco8r8AGYWpSy8/gfkrDi2mhqfwXiufFgbxL265+R01gJ0cMEGTZRyQgRf2XJRAFqUJSnyb7swhb3QyjMpDTaQmD/UsCx9vv+iBcXuXivTCfCQt9LY0V5fS/35U2kJbdr1ZtxKW1hiOcPxSTh5AnuFqJMF/inzShIxQc6vJtZVDzFYWlR8vqHiK2UyIGh4T4Qf7BM3otXcOLItmJTQ="
    }
  }
}
