{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "space_ruin_blacklist",
    "namespace": "persistent-outreach",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "space_ruin_blacklist",
        "namespace": "persistent-outreach",
        "creationTimestamp": null
      },
      "data": null
    },
    "encryptedData": {
      "space_ruin_blacklist.txt": "AgA/IsMfWbYG6pMNLbVWROWkHrGrJbk97GCiTyJLhQeppHeJtqYPoBYVdjUyoIFiZrJoIZ/IHjeK46bgnj7pyhfI3/gQ75atbqVwiHgy7RDivuPjUqjwJcTL1L/6bemBywcf7U1wdr4gPyUTpG24qvf4q7EU+etnBG/PLVrdRen2YIyURA1p+UzwrxS0mzmAzjgScCa8RvSXJFMhfkAm51B6m4bq+4G7uNquP0qigrvgdLulK0sWMAzqknwZGzdV1MbNKSgVwCtrKLXY5v/yGlXJKg0Oj7Tv3HdHBE9WUPDh3I2GYYd/e6b0hCzjgLJuVNJsN4ofDZlklB2XYm6kLVsha77b7mWRRpI7GVRQemJymNCv+u971b22EUcYV3GskhJlOqpF9QTdejScAzH4ZYLEbAEEuvNM8eh1Ob4/bPnz9v3LoYffopmvAnisG5QY20oYag3XRmilBM92/1hsSK/HeFuJk82d6I4lstxS0wpDZym+Oid5b1lfwfxcrIVqqVNNtl2KI2Pmz3xKyXT4PiJ3+AoXqa4kDhsd8JcLMZG+In2jcZgh+3BA+hHTKFmH6lPTIOQ5sBMek76br3JRIiK+7sqVD0tM8DpH8Vf1j1g4fAEqjEm2trzkFunVpOiI3Aw2qFeSSykLpDcyoBoJMQ4TThrQtRVm/ZmZK3adZI9Qmz1d+Cj88ZhsDaMHd6ZM46doWotvZcCrI/lu2LOx21lnVxRP6RhJi8oUNjz7aWFGKNF3viLnlHj3cGDwWuqp9/cW8TK51F7oUT8ayyKTJLIUVTya19B/HOUAr3tflMDS1pK3X9dhqOnt/f5ptUUxsjzU9zamq4QBqseDuMXKppozIkA/tatWsqK5pXWiqW/rJ6OBQ0PTTird/yByA1WFZqp6IXcLA57OeieWabVS11/Bhz72sW3wGZD9pB5gJvQy2SFuR9qHvdRg6LWgQj+7k+2adpciFMGR+57TcGvrH3xIgg=="
    }
  }
}
