{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "custom-sprites",
    "namespace": "persistent-outreach",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "custom-sprites",
        "namespace": "persistent-outreach",
        "creationTimestamp": null
      },
      "data": null
    },
    "encryptedData": {
      "custom_sprites.txt": "AgBItV1JV4A5Fk/tg94r+2DOhtor6YdIxcuQbVlcqQo4sHv8Zi2RcspNoiHDi7IIYkG4j6SyU9YG5Xy/YQRLE9YnOT05VZ7oZk69107MiMc5OTkqEFS0wUJgvFC2mUaaOfyVq+HxsJ7hvft8wmcLrFzRHPamYnq5Gl5iUsH1Zm6h5SniYPUGKJ5z4iuvSlEoFSD7elW7N5dP6DveKe1veVQRq2fNKfIR6OgzJDZfSkN8pWMTHyhGsPSbKlSFw2HLFl9vS2VDJYUUnj8cPwbNkEkY01nzy4RG47RGq3k02FwibjCdeXtjd8S+X9BWyiHr964lxJtUGf68rhuYuqe4G67FeoprmvcgFhAs/FlXFh15+gUiSAsIMWt3ZYFGj/FuZPeazdmRhLc9fAOheZSUmQKnv/oTRz/g3sCUsT+Z9aVZIB7FEMrY68ZgqbzjLTWG9H5ieTPrH/DQanC+uns5pdMh6xT8/ZgVUcrRpq/DxIeV1WjY5yGKJZJD4NIyCH+75AIXV7+K+F/+DUE05OUhI4iE9V0JXJNzJHFRPmj/dQnnU3WA5TSHxgipMzkpPVrBWn9WcJIs6PLDdzcQwBmKTAwzsxicy6LBo5jrQcK4DczImAa56/oVA+bo+B7Ld4wofSOT5+hA+ihsJdW3llCzoJwAXmXhjhqJQeq42UNqxrdTN8UEZwfwATHZw+4IRvBFUPrVgTSZCYq7dycE"
    }
  }
}
