{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "admins",
    "namespace": "persistent-outreach",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "admins",
        "namespace": "persistent-outreach",
        "creationTimestamp": null
      },
      "data": null
    },
    "encryptedData": {
      "admins.txt": "AgC4S4/wN8TLyf8lqeqA/V42SlzsQdISUMOIzKFnV5gfF+gecCWsIOxJWHgp7V8mGHsYO9OE1ymcyNSgqTvtlk7eca1I+Lcb5am4ps3kRVOLZ7/r5V5YWkOklTlCVsz5hlthmMkJlf9kB+/452VkFKJaTJUwQEclt+OcBFA4Q/+ox+EUDXLmqAf+NIcvHYbyyUnNiXD+CYQ2SBwqjC9iXyR+6RYt0L8Jn47nuHaGh5ifC21DjPaQ5GgKB4mJVODRux24CIW+tbHfxVG0OR646NdEebNvPa+hAQTA8r7/LOB79BWFdjBg2n4qjs1vd0l0mg38p2lXrDkPCjHer3+o2k6wKO92j4I1BPCtmIG8v2oAbiK2Yd8lO2wuvJIlMk+6VknDl6wvLzQxFLyvKqjMS4R0yyoKpVmBqeN/NbSIVK4oeyowHSQCSp7f7r7tkwDLGM3X/iNR/+zCfStfrflCSuAnaS+qPoNu77/6Ha8EaxcNFYCqQBv+Mgta2zsS/xhenmT5tPeqGdbM4nNDVTuO2wsvd902lKxP0GEzIY5luKAmAqQkl9xC8t6CFhcTe2vg1evHXCzaQX/1GHxzyvIgFjLaBqV3yCjxwz4Wy4Wq1S6XB2MOP5nx3Dz74S1WG4TzffwidyrEZ9Xc9Q8peV3hwW+TlMFUngaM//o932biLKMO9hKhQXrkKlqpdg/uGnPW8M3fqtROPhZfuIRALShWwj2ad6qgY/DcDAbu9GnfH2M+0ne4DgQNl7mDpbZrU3owbaj7EMTMwLUI7HgNjM//Lem6OdM7xnYUDtWpJTFqN7k+FMpx7c1Zgzj1EASXeKpfD9NgEcMpUIsglFvyQweiZPhWjme3KiLEmmoenKkPKaXk5PYQqmkofN8+T7xnlA8y/NPC1rJq4xPKhA+LyvCQcGq657WZtJ1982uXJYK58Of5iqoDf0uG+bdKl+mIG05pC2GoHmhS/o9s6VtLjQ8RMVFXzFwDxs/rclnN669qYy5dK1qQvYUzJgpkVqX2EjpEtUJusX6BmbNZaci1NlsUihvReupTvoYrh0/7Mwg4D6FkKxNWsy0j6zfPt4EiIsz63CIG3qBU09DG51nP8g1iLyupXB/i6SKNoakIfGlOR9F3j+9V7RqzYF3gh4XhZcVypuFvbP6KPpmS6z3F8MDfvfovyp1UGJeF/OfGt+D9dTVjaNuBi9CbffV6PHYG0mwjcbMlmXuZZWqlMwyjHhTtxs1Bi/GpRAveXQn7jukIhuZJndfiYncpEA05OYOGQDFYA7qMe/qkq414OqqsHur/ZP8gatgRcpMfHaNNxQNjxfqY3OIKalawyZ0tgEASPixERgVyFIf2ylAD18SBYvdgjWxRAYdOB7eINIx29ISNcPVQtozWGyDOEKzKvzF+IiEAtm9ZYCpDwMjnUFhShhdydOv0Oh5c8A+C3WJMveW2RSN+kpO+OL0l2Bdg1ph419q643n2uQCsIHAHaHSAYP0YPHKgsSDeZZ5WkkfwjAAF/CXEVSVRAp92+kC4h3IBw0CFFffjfMVzdlahiCA8u1vsQb/xd/zUrDlq76hSqkJ8Uay76pVkfJN6B1K9JQx0LJau9512vVeWsU/mfsa/CS+oWJX3RcKheC260mqqCuyLkcY18N0rFvK4dGM="
    }
  }
}
