{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "motd",
    "namespace": "persistent-outreach",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "motd",
        "namespace": "persistent-outreach",
        "creationTimestamp": null
      },
      "data": null
    },
    "encryptedData": {
      "motd.txt": "AgDWSOf9DT+++MZwjz8BXEgnjGNiJQZo+ykln0nyx6O6WmTTTi5en5gYQL7W81xj5of5XeDV9rLezTVEimGYx0ZxZmSAOcXJf9qRJyvC9ZnKtj0pUvfwdbcPZNgn9sHB+LQkZdNrubBbsp+G/+5V2SPWbdNYBPoeIg/MNvDlaORUQsBG+IZDl7MJnhToJk3BsGbKPCgnSmEdXDuNMecTPyw9pxnFjLVk4uu0Hj+VZHliAcx3qrk2p8JN532nqTUBgwwzZdg+ehDbHVaZSz24LdWHJzknJdgpEpzjMZfPsQxwa99Q5ENfT0TzcED3HlMo1FJIhuuDAOUxeaR02LViNzsNKMMI+xpr/+YTCio7mkq40fihx2NXHl73iAGLcdWdEtyAsCpdCz18hZ3tnA4ggY3Eqo0gVfv0aJ/9xlUAfUSA1z+0XQ7tDyU5DpTIHWLXoQOMetmmoX6uRBzsFygVxR+CN4mq/roD71Kfk7yCh3RMv3v4fRXg1sAYMvawbxS3dL0tUc0FLzaiUC4bXR6aorsoSGx9Fy9HOK40rZAh0mZEe7Y85gWiL5zNMIPMuEJVQE6IZTvEmo89bNCZOYhAJd6ZoV5MbOm1rpJtg2RIaKfccyEWwP3L9Tkh1FpMW6BN4yX/IoCg8dWcSQP4iV4Svhf/QMkVwvXaD8CQyf7g09J0/vjrnq2eYQAAalr1F6vLst+jMi2ycwJLJnlnsG9HRksMK9gbvO+FNxjtLmaNTFdhdHc21gRWzugcsPqGDV8Ut8GeDDomKmTeNQAUdLPQOMfYrEq8mXKXB6lBFOrsRk5XPXBrXw/AI/7QoLyKdjdWRpvpx44lzhhrqOZZ9Rm/Cx5Hz1nQq2Hp8oaTFHvALDmRNVqc47sWv2FhGvqJTs+MbjrYf8T+wcsoMLmFWfx0QbJP9e2SrkPKyo2UnnOXkVOL22pc+mk50yL4GVbf+Q4jEOcVDjjrvtcsjpaKdTH7C+Le0xIxcDn1sSwhV/XSG88JD4+2j0PnUjUnqOJmpA2GnMeNgeeHZ7OJjXIPOSPwoWyNhuFVI9sMktxVB1Gd9Sjg9hqkM3F1tBthXxgqHfXia/UNF7k3qt1U6jpJjyBNc3uHWvjQqFE/zcXg1hSdU5w4zmfu3QvC9aR5bd9T+l0K9cth1TCzbMwYes5P5iKlt8f+ifD3F0OoDNr2j2+u9A+2xbKOvqdxTDhOXhSJUfw="
    }
  }
}
