{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "away_site_blacklist",
    "namespace": "persistent-outreach",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "away_site_blacklist",
        "namespace": "persistent-outreach",
        "creationTimestamp": null
      },
      "data": null
    },
    "encryptedData": {
      "away_site_blacklist.txt": "AgA/by9PQJ9tPtwBRB0JCeNph3zi09snCpcSda9SD4wxI3Eq8h1Behc9UVYbrofSi+sgTtsEeuNBQS5yaHxHmnb45EO/P6qbwtus/AbhbE2HVSzlke0Zk6xeNW8ynIbu1T+pK0WFz4LgpkuUwT8FLHM6b2bPbbRCfFk8eCkEVPLSGWdBUWy1U55CsNec6Pd16ptK3BXnyjraBrwyrDsEtWDX9b9TlSK7viktcVrXI+bXtQd59CjSfzG4uO4p7VDx/RQi8bCYqEl3HUdgwaC1tYpJv4hgBc2W2NqT74+lSAJqA9Fey/S2dn4Mwk8q1cOgh3vqirUWowK30njrtTDhes/HG1ghZsv6YornFaQptIv7FixDkuCgumBKpxzKFHiDe+kHh2pZAtJ0O2fvuDmw7D4QA+XJP2scY+BQrjUjQtx7bE0ik8PcWAGmncnuXzCWODDT4J6DeoiGFY6WYUtINaoC7VLqnkgMdOWzQA/3Fhfv6PsCTU9KxecindBCjBOn/zBVie0NmIDH7Q4jSUNO9GSBehCu1NUOfPFLTdtITKdnZzsSmCAiSXqy73euMoIorCcrIg4LG3wszCnkiDdSWd/elslT4l8ArSlTXN9DZ57Ey5GEVGfgPZsiWOZEnbkdfHR5yJXUNQ7tHVumzr3shIWOiKeRwGImmRgv3ao69wKoZWaAU1yfed6fKhOpKuBF8PRxNP+lbe0Dt6HaJ9MQzj3ukf7D//KSYLgQX6Av/bmegLZpguCGTpL0y+HrKhMmVvjS2huNwshnvDJEN98MUt3h+6BNLA7Cvm9rjo2JESSQBAeseES6XTCQSjKMopygxz0rNFKqBJBKxKcbAZPeHeCyAUmc+wZIjTIyW+3/PQ0G/7Kyew4Y1Y8RrA3IwT+NDamr01cj9UgztR7xx+AsyurH+rP+BpWGrE3r1TP7VS2H9KRiplvIWi9hLXcSUlYC3a/RTRj8gPPgMWvZL1wHqMMuYdzJjSQ="
    }
  }
}
