{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "space-ruin-blacklist",
    "namespace": "persistent-outreach",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "space-ruin-blacklist",
        "namespace": "persistent-outreach",
        "creationTimestamp": null
      },
      "data": null
    },
    "encryptedData": {
      "space_ruin_blacklist.txt": "AgA9PxbwMdoyra6nmw2BBS8XK6XNr1CQkx6D6ouxM9fv5CgzKVlL9uP33O3c1pZbbJ7d349p+YrfmgoK90JmjcxTvDq4FNULXaDYPrWmsMOwJBv2/3hKKgiWWcyxttlNagXzrAw9fbTMRffGEJ/feoSV3MAqdGFQQ3s3psQqbF2zVj7YeyG6cVOYZFxrQCHSfaMlbvi+K4MTt6TFbLhg10sRnjb+9WM93QNX3lRU16EPbJbdAvMEMuO2QJniReDk6KBqwj3pR2tFBmRvAfXd1omoWpfeqtl8dZLlH2OeutCl/0746E4VWfNWCS0eFR6rhW1K1FZSRIjYAyj7EUHrjX5Fjr/zSafLqJwxNaMqGeJh/pVoIW2VlKGcNjwhxA0p/MF16Qz2hanUb6/sxIkw1YyXhuZsVBi0vsSabuy4/LhbKA1D5TrW2zBf58DS1w3W48xS+VZpQfpAK0ZmOsqI5gd/+L1ldzGwHjEz0hWWODMJYesIyDvkrQY80u362mgZWJMNTo08f6MyMv1YHocSXyL4MM0grEe+o2B3Nd1oRvRX51zeOUcAa81eVoLPrH79y4iDAkhdKutuTqSyWKIhk2vVXqPD4rnIC25eY3vdD2mbduw0iJeBGJceq2TE+wXg4m6pAvRUsTv8YmK+XdSYFjhz50T1Bwg2zAPNrjTnjYgOm+cGtOASVNmnjAtYvvrGtBkW35HbFdATFjlcrX185cUPhr0gGG8nJW30MqSJi0yQKphBlxzWwgk2DmmWBYRAeCnYr6L1vTKDbfwK4Z1ZaeoHl7GSnB5fR6IwAlwZmi8tvDRQoMCOEUNjZmW3hrBfnN6uiqgL7aqzmfxW7y5jR5ppwjGXykRpmzCGESAf7k4AIfazkabeq2V9P7/9ievHb4m+e7xw0dUHcemfK7uWy8T3cSvlHi2yMJvojDm3B2qzett37tXu8vgkr45iqHZC51Nk7/jsPN1IXqkXXvAzguDypQ=="
    }
  }
}
