{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "away-site-blacklist",
    "namespace": "persistent-outreach",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "away-site-blacklist",
        "namespace": "persistent-outreach",
        "creationTimestamp": null
      },
      "data": null
    },
    "encryptedData": {
      "away_site_blacklist.txt": "AgBq7baVsM8azhWmQMk0Jd0wIVvSb+qSATve+Wn6pwsD0lhngCsTMml6ZGfbQrpBSp4vtV3vz+yUye2iDgPqTfth5VVZIuneqrFAlCkKJ/1aEdNNPSy60K+uscnFHOQ7DdxQqpcwT6j/tpiLSUBKncqLy9voqesfanU1rP4ygIxbmzlUs/0ONgELI/8/Wjj3N/ATGfle6akf8q0A5sJ/BaymQSEU+Ab3JA4EQgv5NsazEDi7pCKxghw6wf3vWZ1vpmLZOGQenP1prnQ6utcF6HjmgCQ1LGHh/9JEZ5Jye9JBfVOjsw1cK4QIHrbEu1jsjmsHXUmKF4FcoX3PYEJRHBjG0MSji2Z4T5mBQ4oOa8NpcfUauLjMavr9nRH44+mXQ1hYai9gbPR9UKUUzKp2/MjqHn7uxtpQIrKb5nLzgP953nGhvMQQU5/skZoPpUpfEea+o5f+2XA/0TqNhfZMoLG9nnZy8FOVE7VsD04ABtq32jj0ZeHSY0B2H9xb5RRZDF9aOM6TcKPD55UTqNaL//AQ3ogkKRnFLbVdkGDO+DuHsBK7PACzKwRGyIqDhdX4bNJH2+7cPGLOUsd2WoLts/db4opY+NB4RervjHzXiQNhmVux6jTYrgTF6PYuZD156cfI8CTU4DmbLUEFyRTCV5jLkrSkEvmvs2b8mvaFgYFTINYJG1LE+ZEYChqoPx6XBq6LSkcKegbazgiykF7hDeIEhzcSJhw7JqlwMnZf2usoqAQZML6OSFMo6r97m4DzulqO1R5gkjZg5mBRWX+kbxDO93gHs/Fhm81tRCdtwsN1KETcBEOPVcG2wLzQtOWw2o/8K3ANGGOAF+jR1sM4spHrHvSgdQVwBTnfvIu1eb9g0o51/WfRelzIQbImD3freJ4EYMOZEejr4zNyeK8m8wgPBYMGgY/ov0zzRmRGVAafHV+yyr7BBnS8EIga45j8oPRTE2+4Le9YcAdkybwQztNmud6DDpY="
    }
  }
}
