{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "admins",
    "namespace": "persistent-outreach",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "admins",
        "namespace": "persistent-outreach",
        "creationTimestamp": null
      },
      "data": null
    },
    "encryptedData": {
      "admins.txt": "AgC1pVA1LRiXrm/LzHo+fbPaO85QIAN9syO1TnXcUXWjL3hgVW12wre6jRrulHcPOWRrFgeUOWPaodWcVeJvC0D4vADqEDXBdOU++OilsDp7NNk4WfSQWD64cHYXC2pRDpQmoLDGUAiNdn5XfMqZgwZMAYiv9RA0BKdZamQZZCx1xj3cteMoHBQhB5e4BdWapFtZ9BB/c8AKsmPQK5eK1cE/0eB8l8ODndjcuqfSdAjLPV42fUzSr0PFUIeP/jSlFh8uEkI39CjFoR73JcpcgjysQkBTf/M1GiqGDhVnHE8H3H2/4J3EG6B3/t69v1+tgVaJw6V7+EDMY8qqoFlwNRTmVhcE9KU6V+cKCIuRKSb1OVTTrqAzxziuVJS9FSlnUgtndBVAtvKqcBbg0gFDQmY+EiWK9DxSCQ8Xw0n+RXSWJWEfJWq6dOUFXPrhny/XpovIi05dPhl14Gd4fABIv6JyIJDrpWLqR7FblM4HyAi/fLRMRKoMhE9vvRJZUiUYtyCiPbtk5MC1wKJCKfjYkdP+9Z5ma8m07h005PclXVrcvRXxUmaGiumSIdCHshv4EE1QFKYV9UYcn6vmI/uqvXKD6Tpapz4wplcSnRjySqCBb6Xs7k7foeCgZasekX5ojyMKDMN2k+w0ZPd7FOc4TOcouG/WGcrmuRF3MUxuoS6+gJG1muTlubz389H5jF0ZFmAlvSiRTtkxZrWovMlGuISvKJfd568YW6qqJXxx/mC2cAicpclUgfRbykKVbB3wKvX3OXXjrhq4Scuk/oST3LZVqyKV3T+c+sT0Nf7vYlb9A94uP4bWAumW3mpKDY86Lj0+fI8zNvzXPx+j0zWw2oFfLhHQPZ/0uwY3ngmrcoE4YRpFj6plcXIIrdpWlg9d4ZsYAQK4Si6tyf3/dZktqwmuL9+0gDWCO/ia1xAbVwdoyWm6u75+fSjs/4c823bcQ+ZxTdejRsqeonLCrIM/5m7YQjlH8yzWo6rxBljVMxdjz8tAOSTKKOgIoI4xRAyjYO9W1OAEDY9cP9Mb6DuKxF5Ua0mi+Xl70RFuCmQPt3CFIdyq/emihnhix6F7gBt4aWmsOPpGTt6aYcNDiYXDUCFJgxxK2aEGwXUwR8WE0QC6fUofvUnSo2PL/c3NbY24FOJSeT/MG819VGxwZhbtg7XEgBA5vveXa0vnN/wixy/SVLB7cYtbUdT6jdhGH1dnUUDHwUUPzY7JYk0issYeH5H/z3sxR4+4NL/YkUliRulx+uO/mDY8NrRe5tsyNaHKbHDwzM3xPgd/rBx2rV0cPvDIx2bMfWSHYrDjEIU7EZYPiB6kMYlFI/12P685piZk9tsFC6TCeHVOQ/yQ+TwRA9m7eCSsPwe6h6Uou9wyMrFoRPB/BFVzxSHDMwdMXRjPnlil8+INnhmbLSvG7/IjvlPDO3ahcWFJxf8Xt47UDXmz7n2kOmu9UcTQkD2kG49hIlKCdD7Tn5Lx2fTaMLdNmdXtwe4W9LL+uJyFyDwo5xfpecRsvAXB9lf3Pb2QNAAG6Kq7O5Ubx78qOjIkY3NbNEsdL470m6gxPQKdErouRsbMidm198cMLwwCsxWEJ9P65bGQkGhghFyPfA1Ip84bwMENnAj2kdiX6nJaWUvKvm4PHOrm2E8FtD0="
    }
  }
}
