{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "jobs",
    "namespace": "persistent-outreach",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "jobs",
        "namespace": "persistent-outreach",
        "creationTimestamp": null
      },
      "data": null
    },
    "encryptedData": {
      "jobs.txt": "AgDRALaXIbNMSIMweHaIlTsn/Wz86Ekb9q8WiAHlmmeiJ2/gPvd6FFrh6EqYwXrqVTZphYNolkNhG4pFJQzYl9fCgbXpJkmQUTcaVsPZJdkMDH7Of3KSED8RKcbd0AlN0qzvRimfPgf6zSG0slzxiqBSBjZ0vCP1fbXEIwaEPmwktzdqtb0qeDz0Bo1BfS7AmrdAhm23hP/R4TnOomhEULhgis0VcE1xX/XPtID4LoxsMmoShDNOfnOtGkjkjt0J4/WGXU41dGUSFQ6LMN1MC1F+9GqiyHOWZXnESkbV0QVz2+B/snzU2e/c05OM33N1TnWK+VLblTl5hY/lUX9SOjvLx8Ye9EpihFWu2v12vq14UMnwNxHuMG9K7L9SBEyCySx8A0PgjXMDL5xcBpACBzUdzu6OvuD0SknuYmbfQx11nY9xFAksIbtOXW85+W5e6n/kUTGzprw5CJHp/sSWpZuo5s9ASbm9LAMUG5hnAc/yo9YO4KpAFIYK9BkMah4iYugfwRHpXjpO2yAxxeHU69iVgtRZF3tG2g479spYDg0OO9yjYlmvHFE/5HxJ+REuqIM8l6NPBB34rKbtRyVp//IOx+sMl1MTMN3B11KTTHwBr3qZyeySc05PHV4cY1qyp7EZPlBngsSvSpXsEtbxyJRAhp5EWWk+6wxNO3ilnrZTH7Wb+drzEwQ8+6QD7ywtwxYI26w1yY1D5bLnmwa/2C9fpqk7ofOdcyG7p+hBU8Nqc5gvww2NkHgvR+8AYyynSEfjxd6jmKcdJQn0BBkbxyUWZMO0FIrwoGPk59d0a5FSbEhT1Z7Uf2jIdusJ18mFTrgX9nWWfueZEIGyFc7lgzM1IYikc88nAXGnbHzBp47vf7gAz9krbV+PkM5nBvhWuu3YgseF7cR3kMkMHgOCHc7+tZlsPH4anHt9oF4jThtLeAKfhu0dqN51XjJhC1AhB1mqj9+YwVO3raE/8hizOvjtvU478HDR35oKIr+Be7drdoVPAIlT/JRJcFH3Y0XL7SoM8SG1rp0QhKENPqcA+1r3t9IXRZeRLNurBlO3EpEO8gbi9zusXM59NK7maB04lIjZhhOzUpe9dJuUnbqFUuGtxCEBCn/3rPBVggFmot+MO9QMzJvhv5FnXW+xiQzGzreBccMN2BZsNx9ETQeL3KguaO8aha2Wp9z+291dYcDZFpy3lMKxXUTjf77K3u+K/NgEoX3TxwmMFOnvBGuL1dSjkl5E+fsKxKRkJIGy/Blw9oTKhQfeHh19INlHOsnCjB7CcanY6YvjCB7ivsRB8gPIMH80RoWlUQMH0y+cX04="
    }
  }
}
