{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "banned-words",
    "namespace": "persistent-outreach",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "banned-words",
        "namespace": "persistent-outreach",
        "creationTimestamp": null
      },
      "data": null
    },
    "encryptedData": {
      "banned_words.json": "AgDhGDpPSRN5+7JXNlbbkKe1BE6kEvuZgobhH5MvUkLlyfmRGJNEe1Btp22E0Q6QR80eFCxFnezd00qmb+a7QgtnW1neXjD2iPAEz55KCXfOnvfFOf6WrywCbmErIW27owsm9aEO0ZLPwCl1xNizLeli1muOQbbjWy1TUOsF3dD6dh4dRr9+Ea5H/G7hQrYhXGJv7XpR0zNMD6PzZe5w7dLM+xJb/caazsRAKOKemGShg8+2wlQF5wfKNGbg49X6LeWgYwYY3DS7yC7Tsnu9ZCVPG4l8TwJRbaT/C239VQUNxjMaQyf/vCfDMrHBaQ7jjli6jvpMboZwQ6GZDr20jTfEMan3MDaYMPK/WeaeotOwovJ8F9d8ntYT3F3tWT3Thi2BA9qXoHfkE/z4nnujUqb5Ps8rxTIHu6ebEIWp7xEBUC2ezQuwSmqlxYeSMkSTUcx7qf9mVCnD0aVE/sTes3M7oe2ztkp4D+Czp2UsboT/Tr9lDJFe+5+fPGM1SD7oJNk0WnofBRtuGDKXM39sQDfYSW+MxV2vbnXiEtxHzwrClZFj/75a7a2dBGSaA0MA23bZY/Esgms+O6dMs0FmGLaMsW+Jv6OMgAzkdD4nEf78oCDunccAPs8gdhgw9q/P5sGWaC747rOzsHQ42NZePprGIjFzkq1heuoAkINYsRdZtrTWHra7yJXVpS0V1iAh+zET5l0u87CtQ9pDyb4QG+8="
    }
  }
}
