{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "rules",
    "namespace": "persistent-outreach",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "rules",
        "namespace": "persistent-outreach",
        "creationTimestamp": null
      },
      "data": null
    },
    "encryptedData": {
      "rules.html": "AgA/Lf8cDO5BrKOqKd915XWv5Jb/hOU5w8avZrTfYrhKE4IYUM5H/XtnlALn+O7RfwhnY2ivkG5JJfV9d1o5H+KLwMDCSJmDCKm14+1b//3pYm3ecJKn8R8PAqokkRvER36+HyTp+TIWvTluynkT/N/YkXsBIp6Pk87256fApUHd8iPvlvlE3cfAnbEa44HBKispMP3yVd0gvTw+OTlkfLkTi9vygkIspTXM9OAOq1i5W/a7Pb0JviCpMgOIuJf8Z1bv8Po3zhmWJ+XB9zQJx1JyQu7DB2Sfa0N4+OkXMvvxiLJc/YyLoX1P/sp2RgFTZY/v10ll7KJ+Zd6+kP/6HwRhD3Gz3qVRZ31AC2894RcJr0AV0oUVu3S7QArvaY+yPMJP4n8d21BvXod7kazjoVPNtHemy1SKeSM0c9e4sBvSwiBR1RRcb+KOs9dD5F6lZ96wLydc66f4J63GSaXi5YXeGH+SaBHf6Cehf4rVkNhr/XqRiyoEMOBUc4W+CHdTwwnHyRiHqi+i3SDQIn/IffbeguwdV/W+97XLwf0Cpc4/phhI0x7k8EXuik3NKvW38s6mDUSXWZi6bc1m0MIkhCPdSUKzMETKX3CTBxMSvIah5j79gDtBvsNNlklxzsz9AxEg8VxFiaOiFSC9s+aSMoST2yku21C6POBB+0bgyVEn1KxuSaUBCp6A+az3NOZmR5oMO+urFZmRab3KaVzxcMtgC2DnkDbMG7Kp7mPescSxr1233vnbYV4SgZ03reW5NSyTS4TjMTl8nHYinEkQPltJQ3VZJyHUesxAFd6zYofswJWy0L536QAxf+eAEL1h/q03AWwTUesnTOTMj6QyBOZp1B6Q/MVuUSFwWROdK5uPp+LzGSwzbnXUVqT44uP5iGF41gGdnGse8I1n3H0xZ0UnoSyaWUobWhnOhthzGlgivSL2CtlplitWoheGSNNMzlBTuTdowFdqjzq9eA7YaiGzHf4YxCUusA2cOjUqjMWHmK3EjrsTKbpxcTlCNKUVDWSVfJyuXa5Ou24cz6DnMLKlm+UNRbJhQk34LUNpe9kemRNWJ9xU5N3V7gzRcJD+8vf5"
    }
  }
}
