{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "jobs",
    "namespace": "persistent-outreach",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "jobs",
        "namespace": "persistent-outreach",
        "creationTimestamp": null
      },
      "data": null
    },
    "encryptedData": {
      "jobs.txt": "AgA56Mir5xKABqROhQOHeRi74/idizr9q/R8j8+s4GI6MFt1QW1/BGyoyeyYA0WX5nbObbI+DntXjEgTXyQRk/PSq7zPuqLK3K8CbJLo1nHP/eGqcSpJa9CIF2Ki3Uc3tBMU3Rd/skEyLLVt7flJSJBfopihJE9ZU+R+Pk9kFfcDQ3YXQo2YaQwYOSuShSB2RKtPhhGosLckwUsXZLLqY7zWRN0UU8PWMT30m57WK62hEyaas/uOIeYzu50/gG9Ha7deBGtKouUSFk+I9cDJqp0MJcQXJHV28xjcfIrXk9ouuAetf4ljR1gDf61Gq4M/d/TTS8MH3I7Sd9Tv7YB47nPwiWGdRWxz4w3ivO2XHk8enEVIvXZJ17oyK3GJBsQLSjZY4c+7GcnNR8ELczO/l7o6RNzRUSGd63iqoCmtq5aH3SVJ8NzLhOQ4FpxYVzhJMauRDr1KJ8XXUV/gdiwcCsVrQM4Q4Ha3+UO5El9AZVG8czGJhuf16iKCMbhP5R3vjchHhT8/A3jvS2G0XFZOxqO9EEr5fPVFRqZDBaxwYesPBE85lPSbZbEXTumqkpPug6Rdvi0UyOOFOfHv/79mNsKppeEhrWJ+PvfepTsRZTDTmCnkJC/P/3yxnChe3MMH7y65R6C/zEE4uRJ+E2TlswPNgDARV/NOR+Eef1bUeTyAZBmlvN+SH1Pg/+G3Fw27MTIqSvZRe7GoyxRPPq0oYrtuy6tt5oSJhepIrQGtT/B8SCu+tj3kE8MNSykCpYv+3Ei7Gj+r/hGMzoMu8FIEMgKyIB0096WZkhtXZxPvnHmnvTAp8j72O213HsT0SgH3r7HrXT0M1LS3IKQKExxANwLhMQwqyFjM71sD5fZpn0p2yaVrPt+ZFsunCFhy5kHI1A1NjfMsDQD029VcCFmVIDxNvO41+iuYpz5HSYFMAWmz8kbxm4vmUFoxVmaKG8w+Tf56JV5FnVC/28MjcEA+T+7HdyCKJwiky4XaBAuVLFaa7hh2tdjv2qERwTT4z/NQ1MDUi9pN6EVMJ3Cszdt2TiUfWdNniMNoSAJ7K7HxcEi2w8GXVxEzjMUyZkcAH7vXTUaY/gV2/0uI+BojNwHeoZSFY5c8MCxq5bPLvD/04+EnMEaa5DBGDbYX0b2kGvH6ndRXLam27/XKXlz9jo5AQzZpBh09xhwDnavn8HPMlhW4F4y6TaBr+OTwQUOAerDsda6T0d9Y8kboM9W1EFmKUilcyz1Hy2YitaOCrFyYdsiGQvq5Po1PQOyRCs3B+WF+Fb5P4CCrvzKw15PByEup3Ou6+QcnWofh9Tw7z7GMFDI="
    }
  }
}
