{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "webhooks",
    "namespace": "persistent-outreach",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "webhooks",
        "namespace": "persistent-outreach",
        "creationTimestamp": null
      },
      "data": null
    },
    "encryptedData": {
      "webhooks.json": "AgCqDv2fHlXKUZrm0Ep5LPf40TJZWty/sOLRzY04SNk59uO0Wd3nbXFJvxt/ambVhKxUzSKWsm7tkCdLMdGAVlMuCILUdy4gpjWSuaN8cohWmMYmk/fmm2v+KiErqq7zMJYOs6PAXRMA2pMuGif+2k5jm5rDu3OZvvEFdD1KZ4iLc8HuaMWvSIequTVO/nB6wBY3kjMM2ghPkfPT0VsxEpZ02YQ17LUMOS8M0BsShaJmyZhFdLlfSyntlISGxSbpg93vy5hfxA4ET8HMhkZIiuYIVhzHA/0e4cg+W0WCVkx6jn/wO6A1WKMoanFNzwdIvD1T/TMo1dKEYJXZTHQdXqMQJcNPXZAB4bx6u1kcY5Or1fPT8TplG9ckEZ6lWDu+N0436ipRBWM98UqkDBe+el73oVI5KRua0ctCsmYIT6vOkWQ1zqop/uYBqPt/JC4uqB7B141ILOYVhIWV/qqbwdPyjHE4cRrzXqyKYN8RP5pJj9IQ+j8+ahdTd42vErqSNRNq+f+yzc878ocg34GA1LT7Q57jyzwSueLvY5BH3WwiCd3OL1u8K+peAs3Lg94DGavaR/Y+ZASssrMYrbPCBjEZyoa6QAOEZ9sR5tSspq2qNbW8INUZX4SnrY2Xw0daQIsdzTS/h6nMkxaE+85yWumUxtK8gDWPyRtQu3fd8/9i0I7z6G0EV6aECysqf+YCNg+hEVJaiv2s8Pobq9muarvqSxmNcCLb0GjmVvv5hrYjz//vuFoXeUftB4ZOXsSd92YU0eg1jRkBWDLmRWe7OvkySANSFvMSyQgDp9PkXuk+z6Oqet8zB3fQFTU+kYnPmaLPRLL/NZ9kBbxWegeUE2xpM1VtBZD/tShkrt/YvXOmiON5RCPx5V5Tm2wb+40+nSsg7GC1682STP3mz/SDVPfxIqkaWGn2FLo2ndqFyCOatKJfI9b7XmzxRypzbT7ZHnZMj/r9OpjIo2/PFD08luvkOOz1uIJgh9SY5BSLqzXN2pjPNWA+2io="
    }
  }
}
