{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "rules",
    "namespace": "persistent-outreach",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "rules",
        "namespace": "persistent-outreach",
        "creationTimestamp": null
      },
      "data": null
    },
    "encryptedData": {
      "rules.html": "AgCe9mottE+jJADt3xstyECjhN+b6qw2Aip7Cbe+JtDZyA/gMpjFYAO0yoHwsXie4T/9m2gHiyjpJf5b2apCs4AQw7/RqSC+HfaWsywvp1vRaVP737QoTRXOP+MM6IN7F18Y9xBENL6kvhvvMnApiDe7gdhhR+GJitHipGEiJGFhI0mbTKOwXCel3gYnEPOq1rz8/aY17G7LXTgCH6/gWR7lFTTUG84DVb0F6ZBgqpBeCZFpDX6CqNbnzNKLRYHsothFL0AQ9ayZDVt13GtHgCRCs9HLXS2zWNww1e9DyKPm9v2kPABBMYl7W2di8CxmDq71+14JPIXUPjMJBKNs3QtYUQVMzkI8ozrTOxuJ+NghpRvY88n1DzoNlEKWTBJaC/53xEh0iM1d8oJx0vTlNJkHQuh3gSr4ry2pLphV8hTFWWfII9qV3XDoxpOMNFxI+0qwZVIWMLDhDdzr+LrESAFkuZYU0cq1e4vrZliMVFzFWXORh2DiJoEQnm9ItP6s3tI+/OB5ilangMVEzb9OjKDlPce8b3VhBgeNgPWkpRbQsizNDxtAVmY50/J2zKolnyKx4+7q5PwSklbZzT1slhSPuRw7ialDHuRCwJ27eeAlhKpS8UYXJutp2/J4DqeEVyf9/Mi4ZfaMYhx7HPsusngc+n9qgFb6cC8Zl5ECSWbjE0+bDFxzfScbyEkm92NgWxDmH6KYPgSQqL0KeXXwgAQbDJXfxPsIcjWBaLvWFrNY6HP+6x4DDKvKR3iQbk3YIRxjt2gOS8eVN9zCZ1ZSWh0woj0+Ka9CIV9tAoTdvU7FrbWMMcY8jF8FV/RPnodRayW3/SanbGsrlWm2UY8Mr3lOoxRVejQ3PxXIngt6ChPmrIv5rkt2FM4FNslCD4AgwpezCiRW6WW2uBdiMFWlUNOl58t5TTnMdC+uxu7htt7xmJl29Mtdve5igxNv/PSAbJlzLnEi0+ZCPs0XJt7kfRyWn4vtmIN/PvpYSUQlvMtObGqo0OFXj2kEtJntL/MQSL+2xeBbqIWh2hhO9tvBrLkDXQ5TroV5i21ATp4t5KzRpaUrjTXoQQm+5zxIsMFwk/rE"
    }
  }
}
