---
apiVersion: v1
kind: Service
metadata:
  name: roundcubedb
  namespace: mail
  labels:
    service: roundcubedb
spec:
  ports:
  - port: 5432
    protocol: TCP
  selector:
    service: roundcubedb
---
apiVersion: v1
kind: Service
metadata:
  name: roundcubemail
  namespace: mail
  labels:
    service: roundcubemail
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    service: roundcubemail
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: roundcube-ingress
  namespace: mail
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: "m.milkshakes.cloud"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: roundcubemail
            port:
              number: 80
